- buildSrc/src/main/groovy/com/github/piasy/okbuck/generator/XBuckFileGenerator.groovy
- buildSrc/src/main/groovy/com/github/piasy/okbuck/helper/ProjectHelper.groovy
- buildSrc/src/main/groovy/com/github/piasy/okbuck/rules/AndroidManifestRule.groovy
support different project structure and support multi manifest files merge
> support different project structure and support multi-manifest meger

- app/src/main/java/com/github/piasy/okbuck/example/MainActivity.java
- buildSrc/src/main/groovy/com/github/piasy/okbuck/rule/AndroidResourceRule.groovy
This is one of the biggest hindrance to adopt buck for gradle projects
Fixes #53
> Allow generating R.java of all dependent R.txt of an android_resource

- another-app/build.gradle
- another-app/proguard-rules.pro
- buildSrc/src/main/groovy/com/github/piasy/okbuck/composer/AndroidBinaryRuleComposer.groovy
- buildSrc/src/main/groovy/com/github/piasy/okbuck/model/AndroidAppTarget.groovy
- buildSrc/src/main/groovy/com/github/piasy/okbuck/rule/AndroidBinaryRule.groovy
> Proguard Support

- buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/AndroidBuildConfigRuleComposer.groovy
Mirrors the behavior of gradle
> Fix applicationIdSuffix in BuildConfig

- README-zh.md
- README.md
- buildSrc/build.gradle
- Also improve some documentation
> Downgrade version to 0.1.0-alpha1

- app/build.gradle
- buildSrc/src/main/groovy/com/github/okbuilds/core/model/AndroidAppTarget.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/core/model/AndroidLibTarget.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/core/model/AndroidTarget.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/core/util/ProjectUtil.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/AndroidBuildConfigRuleComposer.groovy
add debuggable attr into merged manifest;
avoid call abstract method inside constructor;
> add debuggable attr into merged manifest

- buildSrc/src/main/groovy/com/github/okbuilds/core/model/Scope.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/AndroidLibraryRuleComposer.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/JavaLibraryRuleComposer.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/okbuck/rule/AndroidLibraryRule.groovy
- This uses the officially supported `provided_deps` from buck instead of the classpath hack we have currently
- It is not needed for java targets as the `provided_deps` and `deps` are the same
> Use buck's provided_deps

- buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/ProjectConfigComposer.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/okbuck/generator/BuckFileGenerator.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/okbuck/rule/ProjectConfigRule.groovy
Now that there is test support, this adds a test target for `project_config`.
It's Java only since there isn't any Android test support yet.
> Add test targets to project_config generation.

- buildSrc/src/main/groovy/com/github/okbuilds/okbuck/generator/DotBuckConfigLocalGenerator.groovy
> Remove ':' from alias names

- app/build.gradle
- app/src/main/java/com/github/okbuilds/okbuck/example/MainActivity.java
- build.gradle
- buildSrc/src/main/groovy/com/github/okbuilds/core/model/AndroidTarget.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/AndroidLibraryRuleComposer.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/okbuck/rule/AndroidLibraryRule.groovy
> Add support for Butterknife

- buildSrc/src/main/groovy/com/github/okbuilds/core/annotation/Experimental.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/core/dependency/DependencyCache.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/core/model/Scope.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/core/util/RobolectricUtil.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/okbuck/ExperimentalExtension.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/okbuck/OkBuckGradlePlugin.groovy
Ref #83 
Not documenting this yet as robolectric testing support is still in flux
> Add support for downloading robolectric runtime dependencies to cache

- buildSrc/src/main/groovy/com/github/okbuilds/core/dependency/DependencyCache.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/core/dependency/ExternalDependency.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/core/util/RobolectricUtil.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/okbuck/ExperimentalExtension.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/okbuck/OkBuckGradlePlugin.groovy
- buildSrc/src/main/resources/com/github/okbuilds/core/util/thirdparty/BUCK_FILE
- Use group name in cached file names to avoid potential conflicts
- Fetch source jars from gradle cache if available
> Add support to fecth source jars

- .travis.yml
- README-zh.md
- another-app/build.gradle
- another-app/proguard-android.txt
- app/build.gradle
- app/src/dev/sqldelight/com/github/okbuilds/okbuck/example/sqldelightmodel/GithubUser.sq
- app/src/main/java/com/github/okbuilds/okbuck/example/MainActivity.java
- app/src/main/java/com/github/okbuilds/okbuck/example/sqldelightmodel/GithubRepo.java
- app/src/main/java/com/github/okbuilds/okbuck/example/sqldelightmodel/GithubUser.java
- app/src/main/sqldelight/com/github/okbuilds/okbuck/example/sqldelightmodel/GithubRepo.sq
- build.gradle
- buildSrc/build.gradle
- buildSrc/src/main/groovy/com/github/okbuilds/core/model/AndroidAppTarget.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/core/model/AndroidTarget.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/core/model/GradleSourceGen.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/core/model/JavaTarget.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/okbuck/OkBuckExtension.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/AndroidLibraryRuleComposer.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/AndroidTestRuleComposer.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/GradleSourceGenRuleComposer.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/ZipRuleComposer.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/okbuck/generator/BuckFileGenerator.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/okbuck/rule/AndroidLibraryRule.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/okbuck/rule/AndroidRule.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/okbuck/rule/AndroidTestRule.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/okbuck/rule/GradleSourceGenRule.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/okbuck/rule/ZipRule.groovy
- dummylibrary/build.gradle
- libraries/javalibrary/build.gradle
- Provides a generic framework to hook any third party gradle plugins that generate sources inside buck
- Add sqldelight support as an example
> SqlDelight Support

- buildSrc/src/main/groovy/com/github/okbuilds/core/model/JavaAppTarget.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/core/model/ProjectType.java
- buildSrc/src/main/groovy/com/github/okbuilds/core/util/ProjectUtil.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/JavaBinaryRuleComposer.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/JavaBuckRuleComposer.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/okbuck/generator/BuckFileGenerator.groovy
- buildSrc/src/main/groovy/com/github/okbuilds/okbuck/rule/JavaBinaryRule.groovy
Generate java_binary rule for projects that use ApplicationPlugin.
> Generate java_binary Rule

- buckw
- buildSrc/src/main/resources/com/github/okbuilds/core/util/wrapper/BUCKW_TEMPLATE
> Fix grep when adding remote

- .travis.yml
- buildSrc/src/main/groovy/com/uber/okbuck/rule/AndroidInstrumentationTestRule.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/rule/AndroidRule.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/rule/AndroidTestRule.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/rule/JavaRule.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/rule/JavaTestRule.groovy
> Add test labels

- buildSrc/src/main/groovy/com/uber/okbuck/core/model/Scope.groovy
> Avoid duplicate target dependencies

- buildSrc/src/main/groovy/com/uber/okbuck/core/model/AndroidTarget.groovy
> Extract custom build config values in buildTypes

- build.gradle
- buildSrc/src/main/groovy/com/uber/okbuck/OkBuckGradlePlugin.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/composer/GradleSourceGenRuleComposer.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/core/model/Target.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/core/util/ProjectUtil.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/extension/ExperimentalExtension.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/extension/GradleGenExtension.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/extension/OkBuckExtension.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/extension/WrapperExtension.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/generator/BuckFileGenerator.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/generator/DotBuckConfigLocalGenerator.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/rule/GradleSourceGenRule.groovy
> Add ability to specify additional options for gradle gen tasks

- buckw
- buildSrc/src/main/groovy/com/uber/okbuck/OkBuckGradlePlugin.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/extension/WrapperExtension.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/wrapper/BuckWrapperTask.groovy
- buildSrc/src/main/resources/com/uber/okbuck/core/util/wrapper/BUCKW_TEMPLATE
> Add ability to watch any files/directories when creating the wrapper

- buildSrc/src/main/groovy/com/uber/okbuck/composer/AndroidLibraryRuleComposer.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/composer/AndroidTestRuleComposer.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/composer/ExopackageAndroidLibraryRuleComposer.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/composer/JavaLibraryRuleComposer.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/composer/JavaTestRuleComposer.groovy
- Moved Retrolamda to run as first post process class command
- Fixed java class path for post process command dependencies
> Fixed java class path for post process command dependencies

- buildSrc/src/main/groovy/com/uber/okbuck/composer/AndroidResourceRuleComposer.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/core/model/AndroidTarget.groovy
`AndroidTarget` is also used for external dependencies.
> Don't merge manifest in the constructor

- buildSrc/src/main/groovy/com/uber/okbuck/printable/PostProcessClassessCommands.groovy
Fixed find dependencies command to exclude dummy and abi jar files.
> Fixed find dependencies command to exclude dummy and abi

- buildSrc/src/main/groovy/com/uber/okbuck/composer/AndroidLibraryRuleComposer.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/composer/AndroidTestRuleComposer.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/composer/ExopackageAndroidLibraryRuleComposer.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/composer/JavaLibraryRuleComposer.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/composer/JavaTestRuleComposer.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/printable/PostProcessClassessCommands.groovy
Updated post process command to generate a script with the command to run.
The idea is to generate a script with the command to run instead of embedding it directly in the BUCK file, to speed up file parsing.
> Generate a script for post process commands

- buildSrc/src/main/groovy/com/uber/okbuck/composer/LintRuleComposer.groovy
This makes sure that the cache keys are consistent across different machines
> Remove absolute paths from lint genrules

- tools/junit/README.md
- tools/junit/buckToJunit.xsl
- tools/junit/buck_to_junit.sh
> Add tool to convert buck test report to junit format

- buildSrc/src/main/groovy/com/uber/okbuck/core/model/base/Scope.groovy
> Fix regression during refactor

- buildSrc/src/main/groovy/com/uber/okbuck/OkBuckGradlePlugin.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/core/model/base/Scope.groovy
- Also remove duplicates from root project's repositories list.
> Add default configuration artifact file if external target resolves to a project dependency.

- buildSrc/src/main/groovy/com/uber/okbuck/OkBuckGradlePlugin.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/core/model/base/Scope.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/core/model/base/TargetCache.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/core/util/ProjectUtil.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/generator/BuckFileGenerator.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/generator/DotBuckConfigLocalGenerator.groovy
> Cache computed targets of a project

- buckw
- buildSrc/src/main/resources/com/uber/okbuck/core/util/wrapper/BUCKW_TEMPLATE
> Some buck wrapper cleanups

- buildSrc/src/main/groovy/com/uber/okbuck/core/model/base/Scope.groovy
> Fix an NPE when trying to add a project based dependency

- buildSrc/src/main/groovy/com/uber/okbuck/OkBuckGradlePlugin.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/composer/android/AndroidBinaryRuleComposer.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/composer/android/AndroidTestRuleComposer.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/constant/BuckConstants.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/core/model/android/AndroidTarget.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/core/model/base/Scope.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/core/model/base/TargetCache.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/core/model/java/JavaLibTarget.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/core/util/LintUtil.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/core/util/ProjectUtil.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/core/util/RetrolambdaUtil.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/core/util/RobolectricUtil.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/generator/BuckFileGenerator.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/generator/DotBuckConfigLocalGenerator.groovy
Move all statics globals to be instance variables on the plugin object instead
> Fix memory leak when using the gradle daemon

- buildSrc/build.gradle
- buildSrc/src/main/groovy/com/uber/okbuck/composer/java/AptRuleComposer.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/composer/java/JavaLibraryRuleComposer.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/composer/java/JavaTestRuleComposer.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/core/model/base/Scope.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/generator/BuckFileGenerator.groovy
> Add project dependencies to annotation processor deps

- buildSrc/src/main/groovy/com/uber/okbuck/composer/android/AndroidBuckRuleComposer.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/composer/android/GenAidlRuleComposer.groovy
> Create aidl rules per source directory

- buildSrc/src/main/groovy/com/uber/okbuck/composer/android/KeystoreRuleComposer.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/composer/android/TrasformDependencyWriterRuleComposer.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/core/dependency/DependencyCache.groovy
- buildSrc/src/main/java/com/uber/okbuck/core/util/FileUtil.java
- buildSrc/src/main/java/com/uber/okbuck/core/util/LintUtil.java
This makes the dependency cache setup a lot faster and also full clean builds lot cheaper
> Create symbolic links for dependency cache artifacts

- app/src/main/AndroidManifest.xml
- buildSrc/src/main/groovy/com/uber/okbuck/core/model/android/AndroidAppTarget.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/core/model/android/AndroidLibTarget.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/core/model/android/AndroidTarget.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/core/model/android/ExoPackageScope.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/core/model/base/Scope.groovy
- Fixes #354
- Fixes an issue with non fully qualified names in the manifest
- Fixes a regression with lint by making sure min and target sdk are inserted into processed library manifests
> Fix a couple of bugs

- another-app/AndroidManifest.xml
- another-app/res/xml/shortcuts.xml
I had some issues with shortcuts in my app so I added them to one of the sample apps to make sure they work. They do :)
> Added Android shortcuts to example projects

- buildSrc/src/main/groovy/com/uber/okbuck/composer/android/KeystoreRuleComposer.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/composer/android/TrasformDependencyWriterRuleComposer.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/core/dependency/DependencyCache.groovy
> Fix file copy issues

- buckw
- buildSrc/src/main/java/com/uber/okbuck/wrapper/BuckWrapperTask.java
- buildSrc/src/main/resources/com/uber/okbuck/core/util/wrapper/BUCKW_TEMPLATE
> Fix wrapper to have correct delimiter

- buildSrc/src/main/groovy/com/uber/okbuck/composer/android/AndroidLibraryRuleComposer.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/composer/android/AndroidTestRuleComposer.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/composer/android/ExopackageAndroidLibraryRuleComposer.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/core/model/android/AndroidAppTarget.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/core/model/android/AndroidLibTarget.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/core/model/android/AndroidTarget.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/core/model/base/RuleType.java
- buildSrc/src/main/groovy/com/uber/okbuck/rule/android/AndroidLibraryRule.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/rule/android/AndroidTestRule.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/rule/android/ExopackageAndroidLibraryRule.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/rule/base/BuckRule.groovy
Integration tests to come next
> Kotlin Android Support

- buildSrc/build.gradle
- buildSrc/src/main/groovy/com/uber/okbuck/config/BUCKFile.java
- buildSrc/src/main/groovy/com/uber/okbuck/config/BuckConfigFile.java
- buildSrc/src/main/groovy/com/uber/okbuck/config/DotBuckConfigLocalFile.java
- buildSrc/src/main/groovy/com/uber/okbuck/generator/BuckFileGenerator.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/rule/android/AndroidBinaryRule.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/rule/android/AndroidBuildConfigRule.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/rule/android/AndroidInstrumentationApkRule.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/rule/android/AndroidInstrumentationTestRule.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/rule/android/AndroidLibraryWrapperRule.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/rule/android/AndroidManifestRule.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/rule/android/AndroidResourceRule.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/rule/android/AndroidRule.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/rule/android/ExopackageAndroidLibraryRule.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/rule/android/GenAidlRule.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/rule/android/PrebuiltNativeLibraryRule.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/rule/base/BuckRule.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/rule/base/GenRule.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/rule/java/JavaBinaryRule.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/rule/java/JavaLibraryWrapperRule.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/rule/java/JavaRule.groovy
- buildSrc/src/main/java/com/uber/okbuck/core/io/FilePrinter.java
- buildSrc/src/main/java/com/uber/okbuck/core/io/Printer.java
- buildSrc/src/main/java/com/uber/okbuck/core/task/OkBuckTask.java
- dependencies.gradle
Faster than the legacy `PrintStream` API
> Switch to using okio for writing to BUCK files

- buildSrc/src/main/java/com/uber/okbuck/core/dependency/ExternalDependency.java
As discussed here https://github.com/uber/okbuck/pull/482#discussion_r130409329.
> Use "-local" as version for local dependencies.

- buckw
- buildSrc/src/main/resources/com/uber/okbuck/core/util/wrapper/BUCKW_TEMPLATE
Noticed during creating another issue #486 :)
> Fix "SUCCESFULLY" typo in buckw update message.

- buildSrc/src/main/groovy/com/uber/okbuck/core/dependency/DependencyCache.groovy
- buildSrc/src/main/java/com/uber/okbuck/core/util/ProguardUtil.java
- buildSrc/src/main/java/com/uber/okbuck/core/util/RetrolambdaUtil.java
Retrolambda needs a full dep name from the cache
> Fix retrolambda

- buildSrc/src/main/groovy/com/uber/okbuck/core/model/android/AndroidAppTarget.groovy
- buildSrc/src/main/java/com/uber/okbuck/extension/OkBuckExtension.java
> Add support for proguard mapping files

- buildSrc/src/main/groovy/com/uber/okbuck/core/model/base/RuleType.java
- libraries/scalalibrary/src/main/java/com/uber/okbuck/scala/example/DummyJava.java
> Do not consider java files for scala modules

- .travis.yml
- build.gradle
- dummy-transform/build.gradle
- dummy-transform/src/main/java/com/uber/okbuck/transform/DummyTransform.java
- settings.gradle
Added integration testing for transform integration with a dummy transform applied to app prod that simply copies all the jars and classes in the output folder.
> Added integration testing for transform integration 

- dependencies.gradle
- libraries/lintErrorLibrary/src/main/java/com/uber/okbuck/example/lintError/MyClass.java
Bump android tools to 26rc1 to get off a beta version and add an integration test for the important NewApi check.
> NewApi Lint test and bump to 26rc1

- buildSrc/src/main/groovy/com/uber/okbuck/core/model/android/AndroidLibTarget.groovy
- buildSrc/src/main/java/com/uber/okbuck/core/util/KotlinUtil.java
> Update Kotlin Android extensions to use the new libraries location

- transform-cli/src/main/java/com/uber/okbuck/transform/JarsTransformOutputProvider.java
- transform-cli/src/test/java/com/uber/okbuck/transform/JarsTransformOutputProviderTest.java
It was failing with:
```console
org.junit.ComparisonFailure: 
Expected :"/var/folders/yt/gc90t4s9507440dd6ds2jm4m0000gn/T/28737931-16a9-4403-b0bd-57f360839caf/buck-out/bin/app/java_classes_preprocess_out_bin_prodDebug/buck-out/gen/.okbuck/cache/__app.rxscreenshotdetector-release.aar#aar_prebuilt_jar__/classes.jar"
Actual   :"/var/folders/yt/gc90t4s9507440dd6ds2jm4m0000gn/T/28737931-16a9-4403-b0bd-57f360839caf/buck-out/bin/app/java_classes_preprocess_out_bin_prodDebug/var/folders/yt/gc90t4s9507440dd6ds2jm4m0000gn/T/28737931-16a9-4403-b0bd-57f360839caf/buck-out/bin/app/java_classes_preprocess_in_bin_prodDebug/buck-out/gen/.okbuck/cache/__app.rxscreenshotdetector-release.aar#aar_prebuilt_jar__/classes.jar"
```
> Fix JarsTransformOutputProviderTest.

- buildSrc/src/main/rocker/com/uber/okbuck/template/config/BuckDefs.rocker.raw
> Move lint error output to stderr

- buildSrc/src/main/groovy/com/uber/okbuck/core/dependency/DependencyCache.groovy
Also a link to the wiki page
https://github.com/uber/okbuck/wiki/Execution-failed:-Error:-Could-not-resolve-all-dependencies-for-configuration
> Add better error message when not defining a repositories block.

- buildSrc/src/main/groovy/com/uber/okbuck/core/dependency/DependencyUtils.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/core/model/base/Scope.groovy
- buildSrc/src/main/java/com/uber/okbuck/core/util/ProjectUtil.java
- gradle/wrapper/gradle-wrapper.properties
- Porting over newer download sources logic from https://github.com/uber/okbuck/pull/568
> Update gradle to 4.5 and stop relying on internal logic for sources

- buildSrc/src/main/groovy/com/uber/okbuck/composer/android/AndroidLibraryRuleComposer.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/composer/android/AndroidTestRuleComposer.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/composer/java/JavaLibraryRuleComposer.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/composer/java/JavaTestRuleComposer.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/core/model/android/AndroidInstrumentationTarget.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/core/model/android/AndroidTarget.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/core/model/android/ExoPackageScope.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/core/model/base/Scope.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/core/model/java/JavaLibTarget.groovy
- buildSrc/src/main/groovy/com/uber/okbuck/core/model/java/JavaTarget.groovy
- buildSrc/src/main/java/com/uber/okbuck/core/util/TransformUtil.java
- buildSrc/src/main/rocker/com/uber/okbuck/template/android/AndroidRule.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/java/JavaRule.rocker.raw
> Pickup all resource dirs for java and android targets

- build.gradle
- buildSrc/src/main/java/com/uber/okbuck/core/model/base/Target.java
- buildSrc/src/main/java/com/uber/okbuck/extension/OkBuckExtension.java
Resolves https://github.com/uber/okbuck/issues/635
> Fix extraBuckOpts to have more generic type.

- buildSrc/src/main/java/com/uber/okbuck/OkBuckGradlePlugin.java
- buildSrc/src/main/java/com/uber/okbuck/extension/LintExtension.java
- buildSrc/src/main/java/com/uber/okbuck/extension/OkBuckExtension.java
- Verified that the generated folders and buck files are exactly same as on commit 9f981cd44430f1d521c3dc038925a0f13ebfd811
- Fixes https://github.com/uber/okbuck/issues/663
> Fix kotlin, scala and wrapper extensions initialization.

- buildSrc/src/main/java/com/uber/okbuck/composer/android/AndroidLibraryRuleComposer.java
- buildSrc/src/main/java/com/uber/okbuck/composer/android/AndroidTestRuleComposer.java
- buildSrc/src/main/java/com/uber/okbuck/composer/android/ExopackageAndroidLibraryRuleComposer.java
- buildSrc/src/main/java/com/uber/okbuck/core/model/android/AndroidLibTarget.java
- buildSrc/src/main/java/com/uber/okbuck/core/model/android/AndroidTarget.java
- buildSrc/src/main/java/com/uber/okbuck/core/model/android/ExoPackageScope.java
Also make exopackage sources inherit compiler options of the base scope
> Move kotlin compiler options to new infra

- build.gradle
- buildSrc/src/main/java/com/uber/okbuck/composer/jvm/JvmBuckRuleComposer.java
- buildSrc/src/main/java/com/uber/okbuck/core/model/android/AndroidTarget.java
- buildSrc/src/main/java/com/uber/okbuck/core/model/base/Scope.java
- buildSrc/src/main/java/com/uber/okbuck/core/model/jvm/JvmTarget.java
- buildSrc/src/main/java/com/uber/okbuck/core/util/KotlinUtil.java
- dependencies.gradle
- libraries/kotlinlibrary/build.gradle
- libraries/kotlinlibrary/src/main/java/demo/Anno.kt
- libraries/kotlinlibrary/src/main/java/demo/Anno2.kt
- libraries/kotlinlibrary/src/main/java/demo/Closed.kt
- libraries/kotlinlibrary/src/main/java/demo/Closed2.kt
- libraries/kotlinlibrary/src/test/java/demo/AllOpenTest.kt
- Fixes #654
- Added integration tests
> Add support for kotlin allopen

- app/src/main/AndroidManifest.xml
- buildSrc/src/main/java/com/uber/okbuck/core/util/XmlUtil.java
> Remove comments from android manifests during merging

- buckw
- buildSrc/src/main/rocker/com/uber/okbuck/template/config/BuckWrapper.rocker.raw
buck handles this correctly now
> Stop killing buck daemons

- another-app/VISIBILITY.bzl
- buildSrc/src/main/java/com/uber/okbuck/OkBuckGradlePlugin.java
- buildSrc/src/main/java/com/uber/okbuck/core/manager/KotlinManager.java
- buildSrc/src/main/java/com/uber/okbuck/core/util/FileUtil.java
- buildSrc/src/main/java/com/uber/okbuck/extension/OkBuckExtension.java
- buildSrc/src/main/java/com/uber/okbuck/extension/VisibilityExtension.java
- buildSrc/src/main/java/com/uber/okbuck/generator/BuckFileGenerator.java
- buildSrc/src/main/rocker/com/uber/okbuck/template/base/BuckRule.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/common/LoadStatements.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/core/Rule.java
- buildSrc/src/main/rocker/com/uber/okbuck/template/core/RuleTemplate.java
- buildSrc/src/main/rocker/com/uber/okbuck/template/jvm/JvmRule.rocker.raw
- java-app/VISIBILITY.bzl
visibility is configured by adding `VISIBILITY.bzl` file in the same directory as `build.gradle/BUCK` file
This file needs to have method `module_visibility` defined that returns visibility.
Example:
```
def module_visibility():
return [
"//buildSrc/...",
"//plugins/...",
]
```
> Added Visibility configuration support to OkBuck.

- .circleci/config.yml
- build.gradle
- buildSrc/build.gradle
- buildSrc/src/main/java/com/uber/okbuck/core/model/jvm/JvmTarget.java
- dependencies.gradle
- gradle/wrapper/gradle-wrapper.properties
Also make kotlin all open integration more robust
> Update gradle, android sdk, kotlin and agp versions

- buildSrc/src/main/java/com/uber/okbuck/OkBuckGradlePlugin.java
- buildSrc/src/main/java/com/uber/okbuck/composer/android/AndroidBuckRuleComposer.java
- buildSrc/src/main/java/com/uber/okbuck/composer/android/KeystoreRuleComposer.java
- buildSrc/src/main/java/com/uber/okbuck/core/model/android/AndroidAppTarget.java
- buildSrc/src/main/java/com/uber/okbuck/core/model/android/Keystore.java
- buildSrc/src/main/java/com/uber/okbuck/core/task/OkBuckCleanTask.java
- buildSrc/src/main/java/com/uber/okbuck/generator/BuckFileGenerator.java
- buildSrc/src/main/resources/com/uber/okbuck/core/util/gen/BUCK_FILE
- buildSrc/src/main/rocker/com/uber/okbuck/template/android/KeystoreRule.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/config/BuckDefs.rocker.raw
> Move keystore processing to buck

- buildSrc/src/main/java/com/uber/okbuck/composer/android/AndroidLibraryRuleComposer.java
- buildSrc/src/main/java/com/uber/okbuck/core/manager/LintManager.java
- buildSrc/src/main/java/com/uber/okbuck/core/util/ProjectUtil.java
> Move lint config xml processing to buck

- buildSrc/src/main/java/com/uber/okbuck/composer/android/AndroidBinaryRuleComposer.java
- buildSrc/src/main/java/com/uber/okbuck/core/model/android/AndroidAppTarget.java
- buildSrc/src/main/java/com/uber/okbuck/core/model/android/AndroidTarget.java
- buildSrc/src/main/java/com/uber/okbuck/core/task/OkBuckCleanTask.java
- buildSrc/src/main/resources/com/uber/okbuck/core/util/gen/BUCK_FILE
> Move proguard config processing to buck

- buildSrc/src/main/java/com/uber/okbuck/composer/android/KeystoreRuleComposer.java
- buildSrc/src/main/java/com/uber/okbuck/core/model/android/AndroidAppTarget.java
- buildSrc/src/main/java/com/uber/okbuck/core/model/android/Keystore.java
- buildSrc/src/main/rocker/com/uber/okbuck/template/android/KeystoreRule.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/config/BuckDefs.rocker.raw
Follow up after https://github.com/uber/okbuck/pull/715#discussion_r216572018
C — Consistency
> Rename keystore.alias to keyAlias, reorder fields for consistency

- buildSrc/src/main/java/com/uber/okbuck/composer/android/ExopackageAndroidLibraryRuleComposer.java
- buildSrc/src/main/java/com/uber/okbuck/core/model/android/AndroidAppTarget.java
- buildSrc/src/main/java/com/uber/okbuck/core/task/OkBuckTask.java
- buildSrc/src/main/rocker/com/uber/okbuck/template/config/BuckDefs.rocker.raw
- Fix generated exopackage android library rule
- Use exo variant's android manifest for exopackage instead of main's.
> Fix generated exopackage android library rule

- buildSrc/src/main/java/com/uber/okbuck/composer/android/ManifestRuleComposer.java
- buildSrc/src/main/java/com/uber/okbuck/composer/jvm/JvmLibraryRuleComposer.java
This fixes manifest genrule to generate correct merged manifest for flavors.
> Add secondary manifest to okbuck_manifest rule

- buildSrc/src/main/java/com/uber/okbuck/composer/android/ManifestRuleComposer.java
- buildSrc/src/main/java/com/uber/okbuck/composer/java/PrebuiltRuleComposer.java
- buildSrc/src/main/java/com/uber/okbuck/core/model/android/AndroidAppTarget.java
- buildSrc/src/main/java/com/uber/okbuck/core/model/android/AndroidTarget.java
- buildSrc/src/main/rocker/com/uber/okbuck/template/android/ManifestRule.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/config/BuckDefs.rocker.raw
- Fixes generation of merged manifest with correct applicationId
> Pass application package to manifest merger.

- buildSrc/src/main/rocker/com/uber/okbuck/template/android/AndroidRule.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/android/AndroidTestRule.rocker.raw
Also fixes disable_lint argument in the template.
> Add disable lint template flag to turn off lint template for robolectric tests

- buildSrc/src/main/java/com/uber/okbuck/core/task/OkBuckCleanTask.java
We do not want this to override the values in `.okbuck/config/okbuck.buckconfig`
> Delete old .buckconfig.local file for now

- buildSrc/src/main/java/com/uber/okbuck/OkBuckGradlePlugin.java
- buildSrc/src/main/java/com/uber/okbuck/core/manager/JetifierManager.java
- buildSrc/src/main/java/com/uber/okbuck/core/model/android/Keystore.java
- buildSrc/src/main/java/com/uber/okbuck/core/task/OkBuckTask.java
- buildSrc/src/main/java/com/uber/okbuck/extension/JetifierExtension.java
- buildSrc/src/main/java/com/uber/okbuck/extension/WrapperExtension.java
> Run GJF on okbuck.

- build.gradle
- buildSrc/src/main/java/com/uber/okbuck/extension/OkBuckExtension.java
DEFS not required in skylark world.
> Remove unused extraDefs option from okbuckExtension

- build.gradle
- buildSrc/src/main/java/com/uber/okbuck/OkBuckGradlePlugin.java
- buildSrc/src/main/java/com/uber/okbuck/core/manager/JetifierManager.java
- buildSrc/src/main/java/com/uber/okbuck/core/task/OkBuckTask.java
- buildSrc/src/main/java/com/uber/okbuck/extension/JetifierExtension.java
- buildSrc/src/main/rocker/com/uber/okbuck/template/config/BuckDefs.rocker.raw
- tooling/jetifier/custom.config
OBS: Had to put a custom configuration file in the project, which has 4,455 lines.... So actual changes are quite small. Accept suggestions to avoid having to do this and yet verify the correct behaviour of the extension
> Added option to provide custom configuration mapping file for jetifier

- buildSrc/src/main/java/com/uber/okbuck/core/dependency/DependencyUtils.java
Some of the open-source libraries are published with different source jars
This is generally due to people updating pom with new repository to publish to respective different repository
It is easy for gradle cache to conatin both version of the source jars if multiple remote repos are queried by gradle at the same machine.
known examples:
commons-httpclient
j2objc-annotations
> Allowing okBuck to pick oldest source jar among many if multiple source jars are present.

- README.md
Based on my spelunking through the codebase today
> Add some information about local development to README

- .circleci/config.yml
- build.gradle
- buildSrc/build.gradle
- dependencies.gradle
Upgrade to non snapshot release
Fixes #570
> Upgrade butterknife to latest

- .buckconfig
- build.gradle
- buildSrc/src/main/java/com/uber/okbuck/core/task/OkBuckTask.java
- buildSrc/src/main/rocker/com/uber/okbuck/template/config/BuckConfig.rocker.raw
Resolves https://github.com/uber/okbuck/issues/792
> Enable in_build.in_build buckconfig if downloadInBuck is set

- buildSrc/src/main/rocker/com/uber/okbuck/template/android/KeystoreRule.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/android/ManifestRule.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/config/OkbuckTargets.rocker.raw
Fixes bug which prevent okbuck_keystore and okbuck_manifest rules to  be overriden
Resolves #803
> Fix rules overrides bug

- build.gradle
- buildSrc/src/main/java/com/uber/okbuck/core/model/android/AndroidAppTarget.java
- buildSrc/src/main/java/com/uber/okbuck/core/model/android/AndroidTarget.java
- dependencies.gradle
- AGP 3.3.0 brings in a lot of dependency constraints that can break large projects. Going to migrate to this version in a separate change
> Partially revert AGP upgrade

- .circleci/config.yml
- buildSrc/src/main/java/com/uber/okbuck/extension/OkBuckExtension.java
Update buck to latest
Helps unblock #821
> Update buck to latest and add a temp fix to kotlin_home for ci

- dependencies.gradle
> Upgrade kotlin to 1.3.21

- README.md
It takes a while to make a HelloWorld android project work with okbuck due to two issues
1, It needs to disable the android lint to avoid issue https://github.com/uber/okbuck/issues/322
2, `./buckw targets` is broken and we have to execute `./buckw targets //...` due to issue https://github.com/facebook/buck/issues/1930.
3, issue https://github.com/uber/okbuck/issues/797 also stops the okbuck to work in new project.
With this pull request, it will resolve these there issue all together and make okbuck ok again.
> Update instructions for listing all buck targets in README

- buildSrc/src/main/java/com/uber/okbuck/composer/android/AndroidLibraryRuleComposer.java
- buildSrc/src/main/java/com/uber/okbuck/core/model/jvm/JvmTarget.java
Custom lint targets can use AutoService and generate a compatible jar with an issue registry so we should not gate on having tthe attribute available in the gradle file also
> Do not check for lint manifest attributes

- buildSrc/src/main/java/com/uber/okbuck/composer/android/AndroidLibraryRuleComposer.java
When lint config is not specified, do not output it to generated buck file
> Handle empty lint xml config properly

- buildSrc/src/main/java/com/uber/okbuck/core/model/jvm/JvmTarget.java
- buildSrc/src/main/java/com/uber/okbuck/extension/OkBuckExtension.java
This lets users turn off legacy processor deps output if all their processors are already captured in javac plugins
> Add option to configure legacy processor support

- buildSrc/build.gradle
- buildSrc/src/main/java/com/uber/okbuck/OkBuckGradlePlugin.java
- buildSrc/src/main/java/com/uber/okbuck/composer/common/HttpFileRuleComposer.java
- buildSrc/src/main/java/com/uber/okbuck/composer/java/PrebuiltRuleComposer.java
- buildSrc/src/main/java/com/uber/okbuck/core/dependency/ExternalDependency.java
- buildSrc/src/main/java/com/uber/okbuck/core/manager/DependencyManager.java
- buildSrc/src/main/java/com/uber/okbuck/core/model/jvm/TestOptions.java
- buildSrc/src/main/java/com/uber/okbuck/core/util/FileUtil.java
Computed sha will be stored in `.okbuck/state/SHA256` file which will be reused for future runs.
> Cache computed sha256 of external dependencies

- .travis.yml
- tooling/ci/build_cmd.sh
- tooling/ci/lint_integration_test.sh
- Less verbose output
- avoid rebuilding test targets across matrix
> Optimize travis builds

- buildSrc/src/main/rocker/com/uber/okbuck/template/android/AndroidBinaryRule.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/android/AndroidModuleRule.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/android/AndroidRule.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/android/BuildConfigRule.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/android/GenAidlRule.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/android/InstrumentationApkRule.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/android/InstrumentationTestRule.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/android/KeystoreRule.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/android/ManifestRule.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/android/PrebuiltNativeLibraryRule.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/base/BuckRule.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/common/ExportFile.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/common/FileGroup.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/common/HttpFile.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/config/BuckWrapper.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/config/OkbuckAndroidModules.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/config/OkbuckPrebuilt.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/config/OkbuckTargets.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/config/SymlinkBuckFile.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/config/groovy/GroovyBuckFile.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/java/JavaAnnotationProcessorRule.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/java/NativePrebuilt.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/java/Prebuilt.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/jvm/JvmBinaryRule.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/jvm/JvmRule.rocker.raw
Make generated buck file output buildozer friendly
> Use double quote in generated buck files where possible

- buildSrc/build.gradle
- buildSrc/src/main/java/com/uber/okbuck/core/dependency/DependencyCache.java
- buildSrc/src/main/java/com/uber/okbuck/core/dependency/DependencyUtils.java
- buildSrc/src/main/java/com/uber/okbuck/core/dependency/OExternalDependency.java
- buildSrc/src/main/java/com/uber/okbuck/core/manager/DependencyManager.java
- buildSrc/src/main/java/com/uber/okbuck/core/model/base/Scope.java
- buildSrc/src/main/java/com/uber/okbuck/extension/ExternalDependenciesExtension.java
- dependencies.gradle
```
okbuck {
legacyAnnotationProcessorSupport = false
enableExportedDeps = true
}
}
```
> Add support for exported_deps with versioned deps

- buildSrc/src/main/java/com/uber/okbuck/composer/java/PrebuiltRuleComposer.java
- buildSrc/src/main/java/com/uber/okbuck/core/dependency/DependencyCache.java
- buildSrc/src/main/java/com/uber/okbuck/core/dependency/OExternalDependency.java
- buildSrc/src/main/java/com/uber/okbuck/core/manager/DependencyManager.java
- buildSrc/src/main/java/com/uber/okbuck/core/model/base/Scope.java
- buildSrc/src/main/java/com/uber/okbuck/core/task/OkBuckTask.java
- buildSrc/src/main/java/com/uber/okbuck/extension/ExternalDependenciesExtension.java
- buildSrc/src/main/rocker/com/uber/okbuck/template/config/OkbuckPrebuilt.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/java/Prebuilt.rocker.raw
```
// makes only top level deps visibile to public, others will have only local visibility.
// this only takes into affect if exported deps is enabled
okbuck {
externalDependency {
strictVisibility = true
}
}
```
> Add support for strict visibility of 3rdparty deps

- buildSrc/src/main/java/com/uber/okbuck/core/task/OkBuckTask.java
- buildSrc/src/main/java/com/uber/okbuck/extension/ExternalDependenciesExtension.java
> Add option to not generate maven_repositories

- buildSrc/src/main/rocker/com/uber/okbuck/template/config/OkbuckTargets.rocker.raw
> Add visibility to manifest rules

- buildSrc/src/main/java/com/uber/okbuck/core/manager/BuckFileManager.java
- buildSrc/src/main/java/com/uber/okbuck/core/manager/LintManager.java
- buildSrc/src/main/java/com/uber/okbuck/core/manager/ManifestMergerManager.java
- buildSrc/src/main/rocker/com/uber/okbuck/template/base/BuckRule.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/config/OkbuckAndroidModules.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/config/OkbuckPrebuilt.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/config/SymlinkBuckFile.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/core/Rule.java
- buildSrc/src/main/rocker/com/uber/okbuck/template/java/JavaAnnotationProcessorRule.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/java/Prebuilt.rocker.raw
- buildSrc/src/main/rocker/com/uber/okbuck/template/jvm/JvmBinaryRule.rocker.raw
- Order rule param in buildifier friendly manner
- Order targets in deps list in buildifier friendly manner
> Make OkBuck output buildifier friendly

- buildSrc/src/main/java/com/uber/okbuck/core/manager/DependencyManager.java
- buildSrc/src/main/java/com/uber/okbuck/extension/ExternalDependenciesExtension.java
```
externalDependency {
// is true by default
markFirstLevelAllVersions = true 
}
```
> Make marking all versions of an artifact as first level configurable

- buildSrc/src/main/java/com/uber/okbuck/core/util/ProguardUtil.java
Guardsquare has moved proguard to a new package name, starting with 7.0.
This will use the new namespace if 7 is at all present in the
dependencies.
> Allow substituting the new proguard namespace

- buildSrc/src/main/java/com/uber/okbuck/core/manager/ManifestMergerManager.java
- buildSrc/src/main/java/com/uber/okbuck/core/util/ProjectUtil.java
> Only create manifest merger target if the project has an android app or library

- .gitignore
- buildSrc/src/main/java/com/uber/okbuck/OkBuckGradlePlugin.java
- buildSrc/src/main/java/com/uber/okbuck/core/manager/D8Manager.java
- buildSrc/src/main/java/com/uber/okbuck/core/manager/DependencyManager.java
- buildSrc/src/main/java/com/uber/okbuck/core/manager/GroovyManager.java
- buildSrc/src/main/java/com/uber/okbuck/core/manager/JetifierManager.java
- buildSrc/src/main/java/com/uber/okbuck/core/manager/KotlinManager.java
- buildSrc/src/main/java/com/uber/okbuck/core/manager/ManifestMergerManager.java
- buildSrc/src/main/java/com/uber/okbuck/core/manager/RobolectricManager.java
- buildSrc/src/main/java/com/uber/okbuck/core/manager/ScalaManager.java
- buildSrc/src/main/java/com/uber/okbuck/core/manager/TransformManager.java
- buildSrc/src/main/java/com/uber/okbuck/core/task/OkBuckCleanTask.java
- buildSrc/src/main/java/com/uber/okbuck/extension/OkBuckExtension.java
- buildSrc/src/main/java/com/uber/okbuck/generator/BuckFileGenerator.java
- buildSrc/src/main/java/com/uber/okbuck/generator/OkbuckBuckConfigGenerator.java
- buildSrc/src/main/rocker/com/uber/okbuck/template/config/BuckConfig.rocker.raw
```
okbuck {
buildFileName = "BUILD.bazel"
}
```
> Add support for specifying generated build file name via okBuck extension

- buildSrc/src/main/java/com/uber/okbuck/OkBuckGradlePlugin.java
- buildSrc/src/main/java/com/uber/okbuck/core/manager/DependencyManager.java
- buildSrc/src/main/java/com/uber/okbuck/extension/ExternalDependenciesExtension.java
This allows configuration of the external dependency sha256 cache of artifacts to be stored outside the project workspace for cache persistence if needed
> Make sha256 cache location configurable

- buildSrc/src/main/java/com/uber/okbuck/extension/OkBuckExtension.java
Use a fork since buck master doesn't have this fix yet: https://github.com/raviagarwal7/buck/commits/5516bef40c669b88f134aed6ff6f4289b9b73923
> Update buck to 5516bef4 which includes fix for big sur

- buildSrc/src/main/java/com/uber/okbuck/core/annotation/AnnotationProcessorCache.java
Add more context to the autoValueConfigurations errors so that users can better understand missing and mismatching autoValue dependencies. 
cc @kageiit @raviagarwal7 
This may make my question in #945 easier to debug.
> Improve autoValueConfigurations error message

- buildSrc/src/main/rocker/com/uber/okbuck/template/config/OkbuckTargets.rocker.raw
Creating a rule to generate project.properties file for Android lint's jar to respect when running lint rules in the Android repo. e.g https://chromium.googlesource.com/external/webrtc/stable/talk/+/411b0dc6814f358620ee66430b2d067cff06c776/examples/android/project.properties
> [android lint] define project.properties rule

- buildSrc/src/main/rocker/com/uber/okbuck/template/config/OkbuckAndroidModules.rocker.raw
Fixing comment inconsistency due to whitespace, correcting extra 'and' in comment
> [android] fix spaces and comment on okbuckAndroidModules

- buildSrc/src/main/rocker/com/uber/okbuck/template/config/OkbuckTargets.rocker.raw
**
- Removing linter hack. No longer necessary since https://code.uberinternal.com/D6843729
- won't merge this PR until the above lands and bakes in for a day or so
**
> removing okbuck linter hack

- buildSrc/src/main/java/com/uber/okbuck/core/manager/JetifierManager.java
- buildSrc/src/main/java/com/uber/okbuck/core/manager/LintManager.java
Fixes relative paths to absolute so they will work across multiple base jvm
> Adding path fixes for jetifier and lint artifacts on arm

- .github/workflows/ci.yml
- RELEASING.md
- buildSrc/gradle.properties
Fix publish snapshot condition to not use matrix variable for java 11
Add release doc
> Set to new development version

- README.md
- simple README update to remove Bintray references and broken link
> Remove Bintray references from README
