uber/okbuck

README.md, build.gradle, buildSrc/build.gradle, buildSrc/src/main/groovy/com/github/piasy/okbuck/OkBuckExtension.groovy, buildSrc/src/main/groovy/com/github/piasy/okbuck/OkBuckGradlePlugin.groovy, buildSrc/src/main/groovy/com/github/piasy/okbuck/dependency/DependencyAnalyzer.groovy, buildSrc/src/main/groovy/com/github/piasy/okbuck/dependency/DependencyExtractor.groovy, buildSrc/src/main/groovy/com/github/piasy/okbuck/generator/BuckFileGenerator.groovy, buildSrc/src/main/groovy/com/github/piasy/okbuck/generator/DotBuckConfigGenerator.groovy, buildSrc/src/main/groovy/com/github/piasy/okbuck/helper/ProjectHelper.groovy, plugin, settings.gradle
- Allows optionally only listing a set of projects to convert to buck. There are cases when some projects should not be converted to buck.
- Also creates a symlink 'plugin' to buildSrc to allow `./gradlew plugin:publishToMavenLocal` for local testing of changes
- Only sets properties from `bintray.properties` file if it exists
=> Add a "buckProjects" configuration to the OkBuckExtension

app/build.gradle, buildSrc/src/main/groovy/com/github/piasy/okbuck/composer/AndroidLibraryRuleComposer.groovy, buildSrc/src/main/groovy/com/github/piasy/okbuck/composer/ExopackageAndroidLibraryRuleComposer.groovy, buildSrc/src/main/groovy/com/github/piasy/okbuck/composer/JavaLibraryRuleComposer.groovy, buildSrc/src/main/groovy/com/github/piasy/okbuck/generator/RetroLambdaGenerator.groovy, buildSrc/src/main/groovy/com/github/piasy/okbuck/model/AndroidTarget.groovy, buildSrc/src/main/groovy/com/github/piasy/okbuck/model/JavaLibTarget.groovy, buildSrc/src/main/groovy/com/github/piasy/okbuck/rule/AndroidLibraryRule.groovy, buildSrc/src/main/groovy/com/github/piasy/okbuck/rule/ExopackageAndroidLibraryRule.groovy, buildSrc/src/main/groovy/com/github/piasy/okbuck/rule/JavaLibraryRule.groovy, install_buck.sh, libraries/common/build.gradle
With this change
- we no longer need https://github.com/facebook/buck/pull/732
- android jar path for retrolambda script is more straightforward
- we can add additional entries to the bootstrap classpath in the future if we need to
=> Add rt.jar to bootstrap classpath for retrolambda

buildSrc/src/main/groovy/com/github/okbuilds/core/model/AndroidAppTarget.groovy, buildSrc/src/main/groovy/com/github/okbuilds/core/model/AndroidTarget.groovy, buildSrc/src/main/groovy/com/github/okbuilds/core/model/Target.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/OkBuckExtension.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/OkBuckGradlePlugin.groovy
- Change overwrite mode to true by default (most common option for regular consumers)
- Provide option to keep some files from being cleaned up by the plugin when running okbuckclean. This is particularly useful to keep the buck-out folder around for faster incremental builds even when buck files are regenerated
- Also added the gradle `compileOnly` configuration to list of apt configurations. This has been available since gradle 2.12 natively
=> Add support for applicationIdSuffix

README.md, another-app/AndroidManifest.xml, another-app/build.gradle, build.gradle, buildSrc/src/main/groovy/com/github/okbuilds/core/annotation/Experimental.groovy, buildSrc/src/main/groovy/com/github/okbuilds/core/model/AndroidAppTarget.groovy, buildSrc/src/main/groovy/com/github/okbuilds/core/model/AndroidTarget.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/ExperimentalExtension.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/OkBuckGradlePlugin.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/AndroidBinaryRuleComposer.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/rule/AndroidBinaryRule.groovy, install_buck.sh
- Adds an experimental extension for new features not supported in buck upstream
- Adds support for manifest placeholders using our fork of buck
- Throw a helpful error if manifest merging failed due to some reason
Verified the generated manifest had placeholders filled in correctly
Resolves #86
=> Add experimental placeholder support

buildSrc/src/main/groovy/com/github/okbuilds/core/model/JavaLibTarget.groovy, buildSrc/src/main/groovy/com/github/okbuilds/core/model/Target.groovy, buildSrc/src/main/groovy/com/github/okbuilds/core/util/FileUtil.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/JavaTestRuleComposer.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/generator/BuckFileGenerator.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/rule/JavaTestRule.groovy, libraries/javalibrary/src/test/java/com/github/okbuilds/okbuck/example/javalib/DummyTestJavaClass.java
- Example generated java_test rule:
```
java_test(
name = 'src_test',
srcs = glob([
'src/test/java/**/*.java',
]),
source = '8',
target = '8',
postprocess_classes_commands = [
'./.okbuck/retrolambda/libraries_javalibrary_main_RetroLambda.sh',
],
deps = [
':src_main',
'//.okbuck/cache/d101e78e05c3f923f9e6888984f3c78f:junit-4.12.jar',
...
],
visibility = [
'PUBLIC',
],
)
```
- Java test resources are not supported yet.
=> Add support for generating `java_test` rule.

buildSrc/src/main/groovy/com/github/okbuilds/core/dependency/DependencyCache.groovy, buildSrc/src/main/groovy/com/github/okbuilds/core/model/AndroidTarget.groovy, buildSrc/src/main/groovy/com/github/okbuilds/core/model/JavaLibTarget.groovy, buildSrc/src/main/groovy/com/github/okbuilds/core/model/JavaTarget.groovy, buildSrc/src/main/groovy/com/github/okbuilds/core/model/Target.groovy, buildSrc/src/main/groovy/com/github/okbuilds/core/util/GitUtil.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/AndroidBinaryRuleComposer.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/AndroidBuckRuleComposer.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/AndroidBuildConfigRuleComposer.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/AndroidLibraryRuleComposer.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/AndroidManifestRuleComposer.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/AndroidResourceRuleComposer.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/AptRuleComposer.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/BuckRuleComposer.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/ExopackageAndroidLibraryRuleComposer.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/GenAidlRuleComposer.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/JavaBuckRuleComposer.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/JavaLibraryRuleComposer.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/JavaTestRuleComposer.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/PreBuiltNativeLibraryRuleComposer.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/generator/BuckFileGenerator.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/generator/DotBuckConfigLocalGenerator.groovy
- Change base `Target` to not contain any java based logic
- Abstract out rule name generation inside composers
- Remove some unneeded methods
=> Extract common logic

.travis.yml, buildSrc/src/main/groovy/com/github/okbuilds/core/model/AndroidAppTarget.groovy, buildSrc/src/main/groovy/com/github/okbuilds/core/model/AndroidTarget.groovy, buildSrc/src/main/groovy/com/github/okbuilds/core/model/ExoPackageScope.groovy, buildSrc/src/main/groovy/com/github/okbuilds/core/model/JavaLibTarget.groovy, buildSrc/src/main/groovy/com/github/okbuilds/core/model/JavaTarget.groovy, buildSrc/src/main/groovy/com/github/okbuilds/core/model/Scope.groovy, buildSrc/src/main/groovy/com/github/okbuilds/core/model/Target.groovy, buildSrc/src/main/groovy/com/github/okbuilds/core/util/FileUtil.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/OkBuckGradlePlugin.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/AndroidBinaryRuleComposer.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/AndroidLibraryRuleComposer.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/AndroidManifestRuleComposer.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/AndroidResourceRuleComposer.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/AptRuleComposer.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/ExopackageAndroidLibraryRuleComposer.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/GenAidlRuleComposer.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/JavaLibraryRuleComposer.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/JavaTestRuleComposer.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/generator/BuckFileGenerator.groovy
- Condense sources/resources/dependencies (external and targets) into `Scope`. Some example scopes are `main` , `test`, `apt` etc.
- Cleanup the target internals using scopes
- Gets rid of calling abstract methods in the target constructors
=> Add new Scope Model

buildSrc/src/main/groovy/com/github/okbuilds/core/model/JavaTarget.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/AndroidLibraryRuleComposer.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/JavaLibraryRuleComposer.groovy
Resolves #62 
These dependencies are not exported and are only used to compile the target similar to gradle behavior
=> Support provided/compile only configurations

buildSrc/src/main/groovy/com/github/okbuilds/core/model/JavaTarget.groovy, buildSrc/src/main/groovy/com/github/okbuilds/core/model/Scope.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/AndroidLibraryRuleComposer.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/JavaLibraryRuleComposer.groovy
It seems the dependencies in the deps block are not exposed to other rules that depend on a rule, but they do end up in the final apk which is not desirable, even if the compilation part works :)
This change makes the dependencies part of the compilation classpath via the jvm args which is what the provided plugin does in gradle.
See: https://github.com/nebula-plugins/gradle-extra-configurations-plugin/blob/master/src/main/groovy/nebula/plugin/extraconfigurations/ProvidedBasePlugin.groovy
I am reverting the earlier change for provided scope. Ref #62
=> Proper fix for provided configurations

.travis.yml, README.md, build.gradle, buildSrc/src/main/groovy/com/github/okbuilds/core/util/ProjectUtil.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/OkBuckExtension.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/ProjectConfigComposer.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/generator/BuckFileGenerator.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/rule/BuckRule.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/rule/ProjectConfigRule.groovy
This adds support for generating [project_config](https://buckbuild.com/rule/project_config.html) rules so OkBuck consumers can use the [project](https://buckbuild.com/command/project.html) command to generate an IntelliJ project.
Unfortunately, there can only be one project_config rule per BUCK file. This means the the project_config `srcTarget` needs to reference the primary target for the BUCK file.
This default to use the `debug` variant for Android apps and the `release` variant for Android libraries. If a user wants to customize this, they can use the Gradle extension.
Test Plan: Added project generation (using both new generator and old generator) to Travis CI configuration.
(Unrelated, but `project_config` will be going away with the new project generator in Buck, but that still …
=> Adding support for generating project_config rules.

buildSrc/src/main/groovy/com/github/okbuilds/core/model/AndroidTarget.groovy, buildSrc/src/main/groovy/com/github/okbuilds/core/model/JavaLibTarget.groovy, buildSrc/src/main/groovy/com/github/okbuilds/core/model/Scope.groovy, buildSrc/src/main/groovy/com/github/okbuilds/core/util/FileUtil.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/AndroidLibraryRuleComposer.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/AndroidResourceRuleComposer.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/ExopackageAndroidLibraryRuleComposer.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/JavaLibraryRuleComposer.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/JavaTestRuleComposer.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/rule/AndroidLibraryRule.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/rule/JavaLibraryRule.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/rule/JavaRule.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/rule/JavaTestRule.groovy
- eg:
```
java_test(
name = 'test_main',
srcs = glob([
'src/test/java/**/*.java',
]),
resources = glob([
'src/test/resources/**',
]),
resources_root = 'src/test/resources',
...
```
- move jvm args to scope
=> Add support for resources and resources_root to java_library and java_test rules.

README.md, build.gradle, buildSrc/build.gradle, buildSrc/src/main/groovy/com/github/okbuilds/core/annotation/Experimental.groovy, buildSrc/src/main/groovy/com/github/okbuilds/core/model/AndroidAppTarget.groovy, buildSrc/src/main/groovy/com/github/okbuilds/core/util/GitUtil.groovy, buildSrc/src/main/groovy/com/github/okbuilds/core/util/InstallUtil.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/ExperimentalExtension.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/InstallExtension.groovy, dummylibrary/build.gradle, gradle/wrapper/gradle-wrapper.properties, libraries/javalibrary/build.gradle
- Use `compileOnly` instead of `provided` for java projects
- Update Gradle to 2.14
- Use latest buck master
- Cleanup install task
=> Promote manifest placeholders support from experimental to fully supported

buildSrc/src/main/groovy/com/github/okbuilds/core/model/AndroidAppTarget.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/OkBuckExtension.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/AndroidBinaryRuleComposer.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/rule/AndroidBinaryRule.groovy
Add an option to enable extra options on `android_binary` rules. These rules by far have the most number of undocumented options which makes it hard to support them all officially without adding bloat. We can later extend this to provide support for other rules as needed.
Going to leave this undocumented in readme as this api is still in flux.
=> Support to add extra buck options to rules

buildSrc/src/main/groovy/com/github/okbuilds/core/dependency/DependencyCache.groovy, buildSrc/src/main/groovy/com/github/okbuilds/core/dependency/ExternalDependency.groovy, buildSrc/src/main/groovy/com/github/okbuilds/core/model/AndroidTarget.groovy, buildSrc/src/main/groovy/com/github/okbuilds/core/model/JavaTarget.groovy, buildSrc/src/main/groovy/com/github/okbuilds/core/model/Target.groovy, buildSrc/src/main/groovy/com/github/okbuilds/core/util/ProjectUtil.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/generator/BuckFileGenerator.groovy
- Buck file generator goes through each project one by one and to gets all its rules.
- If a rule is created for a project which is very low in (near leaf) in the hierarchy then the resolved dependencies (in the rule) might differ from its parent ones (or from the project in a completely disjoint tree)
- This diff is resolving configuration and extracting dependencies before creating rules.
=> Extract target dependencies and populate cache before creating rule to make sure all projects are on the same version of dependencies.

buildSrc/src/main/groovy/com/github/okbuilds/core/dependency/DependencyCache.groovy, buildSrc/src/main/groovy/com/github/okbuilds/core/model/AndroidTarget.groovy, buildSrc/src/main/groovy/com/github/okbuilds/core/util/RobolectricUtil.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/OkBuckGradlePlugin.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/AndroidBuckRuleComposer.groovy
Fixes #144
- Remove digest calculation from dependency cache to make okbuck task faster. Hashing is already handled by buck
- Simplify `android_resource` rule names when only one resource and asset folders are available per target
- Do not add robolectric tasks when not enabled
=> Cleanup cache structure and remove digest from rulenames when not needed

buildSrc/src/main/groovy/com/github/okbuilds/core/task/OkBuildCleanTask.groovy
- This resolves a transient build failure in certain projects due to xerces
=> Use project filetree instead of file name filter

buildSrc/src/main/groovy/com/github/okbuilds/core/model/AndroidAppTarget.groovy, buildSrc/src/main/groovy/com/github/okbuilds/core/model/AndroidTarget.groovy
This moves the ApplicationId part of the build config generator to the base AndroidTarget in a similar fashion to: https://github.com/OkBuilds/OkBuck/commit/3e3d818fe6ced9d15ea6962f54b73841fe12c1ca
This will generate the following for a library:
```python
android_build_config(
...
package = 'com.package.lib',
values = [
...
'String APPLICATION_ID = "com.package.lib"',
...
],
...
)
```
And remain the same for an application:
```python
android_build_config(
...
package = 'com.package.app',
values = [
...
'String APPLICATION_ID = "com.package.app"',
...
],
...
)
```
=> Move BuildConfig application ID to base AndroidTarget

buckw, buildSrc/src/main/groovy/com/github/okbuilds/core/model/AndroidTarget.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/AndroidBuckRuleComposer.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/composer/AndroidResourceRuleComposer.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/generator/BuckFileGenerator.groovy, buildSrc/src/main/groovy/com/github/okbuilds/okbuck/rule/BuckRule.groovy, buildSrc/src/main/resources/com/github/okbuilds/core/util/wrapper/BUCKW_TEMPLATE
This uses the res/asset folder parent directory name to name the `android_resource` rule target names. This makes the generated buck files a lot more readable and closer to how gradle source sets work.
=> Generate android_resource rule names based on directory name

buckw, buildSrc/src/main/resources/com/github/okbuilds/core/util/wrapper/BUCKW_TEMPLATE
- Handle cases when no previous successful okbuck run or when user clears their workspace
- Set a system property `okbuck.wrapper=true` to indicate the gradle task run was invoked via `buckw`. This can be useful to turn off some plugins that are not needed for okbuck to compute the project model, thus speeding up the task execution time of okbuck
=> Improvements to buckw

buckw
Sometimes there's a need for additional args to be passed to gradle (i.e. on CI) which wind up resolving the project differently which in turn affect the buck configuration. This change allows end users to set the `OKBUCK_ARGS` env variable (and renames `EXTRA_ARGS` -> `CLEAN_ARGS` for clarity) so that any additional parameters can be passed as necessary. Open to naming suggestions here.
=> Add support for external arguments when running okbuck via buckw

app/src/androidTest/AndroidManifest.xml, buildSrc/src/main/groovy/com/uber/okbuck/composer/AndroidResourceRuleComposer.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/model/AndroidTarget.groovy
The `package` element inside main `AndroidManifest.xml` specifies the package `R.java`, the `applicationId` may be different for different flavors, but `package` is always the same.
I'm happy to change the implementation, wanted to get something working first.
=> Use package instead of applicationId inside resource rule

buckw
- `md5digest` randomly fails on some setups
=> Use 'custom' as remote for custom buck repo.

buildSrc/src/main/groovy/com/uber/okbuck/core/model/Scope.groovy
Gradle does not download sources by default. This means locally the IDE plugins that are applied by the android gradle plugin are responsible for downloading sources.
This has several problems
- If you only use buck generated project files, the sources are never downloaded by intellij as the `idea` plugin is not applied
- More importantly, the cache rule keys will be different locally and on CI causing the network cache to miss on all prebuilts
This change uses the same mechanism used by the gradle `idea` plugin to force sources to be downloaded to the local gradle cache so that the dependency cache can pick them up for the generated BUCK files when `sources` are enabled
=> Download sources if enabled even if IDE plugins are not applied

buildSrc/src/main/groovy/com/uber/okbuck/composer/BuckRuleComposer.groovy, buildSrc/src/main/groovy/com/uber/okbuck/composer/JavaBinaryRuleComposer.groovy, buildSrc/src/main/groovy/com/uber/okbuck/composer/LintRuleComposer.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/model/JavaAppTarget.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/model/JavaTarget.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/util/ProjectUtil.groovy, buildSrc/src/main/groovy/com/uber/okbuck/rule/JavaBinaryRule.groovy, buildSrc/src/main/groovy/com/uber/okbuck/rule/LintRule.groovy, buildSrc/src/main/resources/com/uber/okbuck/core/util/lint/LINT_DEPS_BUCK_FILE
Lint has many dependencies and with a bunch of custom lint targets, it can lead to "Argument list too long" error when running the lint genrules.
To avoid this all, android sdk lint dependencies are converted to a fat jar before being provided to the command line linter. Custom lint gradle modules can apply the java `application` gradle plugin to be bundled up into a fat jar as well. When doing so, you may want to add
```gradle
jar {
excludes = 'META-INF'
}
```
To such modules to avoid weird lint exceptions with jar signing verifications
=> Bundle lint dependencies into a fat jar

buildSrc/src/main/groovy/com/uber/okbuck/composer/LintRuleComposer.groovy, buildSrc/src/main/groovy/com/uber/okbuck/generator/LintWrapperGenerator.groovy, buildSrc/src/main/groovy/com/uber/okbuck/rule/LintRule.groovy, buildSrc/src/main/resources/com/uber/okbuck/core/util/lint/LINTW_TEMPLATE
This is needed because of some undocumented behavior in buck https://github.com/facebook/buck/issues/999
That can lead to "Argument list too long" error when running the lint rules on large projects
=> Fix lint genrule to not use 'DEPS'

build.gradle, buildSrc/src/main/groovy/com/uber/okbuck/composer/AndroidTestRuleComposer.groovy, buildSrc/src/main/groovy/com/uber/okbuck/composer/JavaTestRuleComposer.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/model/AndroidTarget.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/model/JavaTarget.groovy, buildSrc/src/main/groovy/com/uber/okbuck/rule/AndroidLibraryRule.groovy, buildSrc/src/main/groovy/com/uber/okbuck/rule/AndroidRule.groovy, buildSrc/src/main/groovy/com/uber/okbuck/rule/AndroidTestRule.groovy, buildSrc/src/main/groovy/com/uber/okbuck/rule/JavaLibraryRule.groovy, buildSrc/src/main/groovy/com/uber/okbuck/rule/JavaRule.groovy, buildSrc/src/main/groovy/com/uber/okbuck/rule/JavaTestRule.groovy
This supports test jvm args set in gradle like
```
project.tasks.withType(Test) { Test task ->
task.jvmArgs << "-Djava.awt.headless=true"
}
```
so that buck tests do not pop up a java icon in the dock for every test vm created
=> Add support for test runner jvm args

buildSrc/src/main/resources/com/uber/okbuck/core/util/retrolambda/retrolambdac
This bug caused a major breakage in our CI server after upgrading to okbuck 0.10.
The symptom is that builds started failing with `ResourceParseException premature end of file`, or `file not found` or any similar errors.
After SSHing into the server I could observe that several files were modified after running buck build, always random files under the same directory, mostly just `.java` or `.xml` files (which was the majority of the files in the directory). I could verify this by running `git status`. For every modified file, it would almost always be completely empty (all contents deleted) or sometimes partially deleted (more rarely). 
I also observed that the list of deleted files was always different and the longer the build ran, the more files were deleted.
After a lot of digging, I …
=> Do not invoke retrolambda with empty inputDir

build.gradle, buildSrc/src/main/groovy/com/uber/okbuck/OkBuckGradlePlugin.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/dependency/DependencyCache.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/util/FileUtil.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/util/ProjectUtil.groovy, buildSrc/src/main/groovy/com/uber/okbuck/extension/ExperimentalExtension.groovy, buildSrc/src/main/groovy/com/uber/okbuck/generator/BuckFileGenerator.groovy
Adds an experimental `parallel` flag that lets okbuck generate BUCK files as a per project task. This can reduce okbuck run times when used in combination with gradle's parallel flag.
=> Add option to generate BUCK files in parallel

buildSrc/src/main/groovy/com/uber/okbuck/OkBuckGradlePlugin.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/dependency/DependencyCache.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/util/RobolectricUtil.groovy
Speeds up evaluation of buck rules by cleaning up unused dep files in various dependency caches
=> Cleanup old files in dependency cache

buildSrc/src/main/groovy/com/uber/okbuck/core/dependency/DependencyCache.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/model/base/Scope.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/model/java/JavaTarget.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/util/LintUtil.groovy
- Move annotation processor search to dependency cache and perform it lazily when a scope requests it
- Only check for annotation processors in jars that are first level module dependencies
Related to #274
=> Improved Annotation Processor resolution

buildSrc/src/main/groovy/com/uber/okbuck/core/dependency/DependencyCache.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/dependency/ExternalDependency.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/dependency/TargetDependency.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/dependency/VersionlessDependency.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/model/android/ExoPackageScope.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/model/base/Scope.groovy
```
projectA depends on projectB
projectC depends on artifactA 
artifactA depends on projectB-artifact
```
**old resolution:**
```
projectA depends on projectB
projectC depends on artifactA, projectB-artifact
```
**new resolution:**
```
projectA depends on projectB
projectC depends on artifactA, projectB
```
=> Correctly resolve to the project dependency if both project & it's artifact are present.

buildSrc/src/main/groovy/com/uber/okbuck/core/model/base/Scope.groovy
Added jdk tools jar to a project. Tested that `okbuck` failed
```
:libraries:common:okbuck FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':libraries:common:okbuck'.
> Local dependencies should be under project root. Dependencies outside the project can cause hard to reproduce builds. Please move dependency: /Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/lib/tools.jar inside /Users/kage/src/okbuck
```
=> Add a check to fail build on invalid local dependencies

buckw
If the watchman query doesn't work out, we need to clean all buckfiles. Stale BUCK files can produce the following:
[1m[44m RUNNING OKBUCK... [0;10m
Traceback (most recent call last):
File "<string>", line 1, in <module>
KeyError: 'files'
rm: missing operand
Try `rm --help' for more information.
[1m[44m DELETED OLD BUCK FILES [0;10m
=> Clean up BUCK files if rm fails

buildSrc/src/main/groovy/com/uber/okbuck/rule/java/JavaBinaryRule.groovy
Should be 
```
blacklist = glob([
'**/*.java',
]),
```
instead of 
```
blacklist = [
'**/*.java',
],
```
Stacktrace
```
[2016-12-22 14:49:38.656][error][command:null][tid:1020][com.facebook.buck.cli.Main] Uncaught exception at top level
java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 0
**/*.java
^
at java.util.regex.Pattern.error(Pattern.java:1955)
at java.util.regex.Pattern.sequence(Pattern.java:2123)
at java.util.regex.Pattern.expr(Pattern.java:1996)
at java.util.regex.Pattern.compile(Pattern.java:1696)
at java.util.regex.Pattern.<init>(Pattern.java:1351)
at java.util.regex.Pattern.compile(Pattern.java:1028)
at com.facebook.buck.rules.coercer.PatternTypeCoercer.coerce(PatternTypeCoercer.java:39)
at …
```
=> Surround `blacklist` property of java lib in a glob.

app/build.gradle
Required so that app project compiles with gradle.
=> Ensure AutoValue compiles in gradle builds

buildSrc/src/main/groovy/com/uber/okbuck/OkBuckGradlePlugin.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/dependency/DependencyCache.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/dependency/ExternalDependency.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/model/android/AndroidAppTarget.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/model/android/AndroidTarget.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/model/base/Target.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/util/GroovyUtil.groovy, buildSrc/src/main/groovy/com/uber/okbuck/generator/BuckFileGenerator.groovy
Groovy mutates the underlying map with the default value when a default value is passed in Map.get . It doesn’t handle concurrent modification leading to multiple entries of the same key.
=> Don't pass default values to Map.get to prevent map mutation.

app/src/demo/AndroidManifest.xml, app/src/dev/AndroidManifest.xml, buildSrc/src/main/groovy/com/uber/okbuck/core/model/android/AndroidAppTarget.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/model/android/AndroidLibTarget.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/model/android/AndroidTarget.groovy
- Do not require a pass of the manifest merger unless there are more than one manifest involved per variant
- Libraries do not need to process the manifest to set attributes like version code etc.
=> Reduce the number of manifest merger invocations

buildSrc/src/main/groovy/com/uber/okbuck/OkBuckGradlePlugin.groovy, buildSrc/src/main/groovy/com/uber/okbuck/composer/android/LintRuleComposer.groovy, buildSrc/src/main/groovy/com/uber/okbuck/composer/base/BuckRuleComposer.java, buildSrc/src/main/groovy/com/uber/okbuck/composer/java/AptRuleComposer.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/model/java/JavaTarget.groovy, buildSrc/src/main/groovy/com/uber/okbuck/generator/BuckFileGenerator.groovy, buildSrc/src/main/groovy/com/uber/okbuck/rule/android/AndroidLibraryWrapperRule.groovy, buildSrc/src/main/groovy/com/uber/okbuck/rule/java/JavaLibraryWrapperRule.groovy, libraries/emptylibrary/build.gradle
This is useful when using newer PSI based lints which can enhance the AST with proper type information when used with the `--libraries` flag.
To make the classes of any external or project dependency available to the buck linter for analysis, they can be specified as
```
dependencies {
buckLintLibray "com.example:dep:1.0.0"
buckLintLibray project(":dep")
}
```
=> Add ability to add lint libraries to genrules

buildSrc/src/main/groovy/com/uber/okbuck/core/model/base/Scope.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/model/java/JavaTarget.groovy
- Fixes #362 
- The android gradle plugin creates many configurations for every buildType and flavor combination. Even standard configurations may not always be used by projects i.e they may only declare dependencies on a few configurations per project. This change filters out configurations that are useful for building and ignores resolving all possible configurations to speedup okbuck time.
=> Only resolve subset of useful configurations during okbuck

buildSrc/src/main/groovy/com/uber/okbuck/core/dependency/DependencyCache.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/dependency/ExternalDependency.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/dependency/ProjectDependency.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/dependency/VersionlessDependency.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/model/base/Scope.groovy, buildSrc/src/main/java/com/uber/okbuck/core/util/ProguardUtil.java
=> Add support for classifiers in external dependencies

.watchmanconfig, buildSrc/src/main/resources/com/uber/okbuck/core/util/wrapper/WATCHMAN_CONFIG
If your buckconfig is set to use watchman as the glob_handler like the following:
```
[project]
glob_handler = watchman
```
then having watchman ignore the `.okbuck` folder causes issues. There are a number of generated build rules within `.okbuck` like those within `cache/BUCK`, `cache/lint/BUCK` and `keystore/app/BUCK` which rely on globs to find files. If watchman ignores the `.okbuck` dir, those watchman queries blow up and the build fails.
The downside of this is that there may be some false positives but hopefully in the future we can more specific ignore or include specific directories for watchman.
cc @kageiit
=> Don't ignore the .okbuck folder in watchman

buildSrc/src/main/groovy/com/uber/okbuck/composer/android/AndroidTestRuleComposer.groovy, buildSrc/src/main/groovy/com/uber/okbuck/composer/groovy/GroovyTestRuleComposer.groovy, buildSrc/src/main/groovy/com/uber/okbuck/composer/java/JavaTestRuleComposer.groovy, buildSrc/src/main/groovy/com/uber/okbuck/composer/kotlin/KotlinTestRuleComposer.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/model/android/AndroidTarget.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/model/jvm/JvmTarget.java, buildSrc/src/main/groovy/com/uber/okbuck/core/model/jvm/TestOptions.java, buildSrc/src/main/groovy/com/uber/okbuck/rule/android/AndroidLibraryRule.groovy, buildSrc/src/main/groovy/com/uber/okbuck/rule/android/AndroidRule.groovy, buildSrc/src/main/groovy/com/uber/okbuck/rule/android/AndroidTestRule.groovy, buildSrc/src/main/groovy/com/uber/okbuck/rule/groovy/GroovyLibraryRule.java, buildSrc/src/main/groovy/com/uber/okbuck/rule/groovy/GroovyRule.groovy, buildSrc/src/main/groovy/com/uber/okbuck/rule/groovy/GroovyTestRule.java, buildSrc/src/main/groovy/com/uber/okbuck/rule/java/JavaLibraryRule.groovy, buildSrc/src/main/groovy/com/uber/okbuck/rule/java/JavaRule.groovy, buildSrc/src/main/groovy/com/uber/okbuck/rule/java/JavaTestRule.groovy, buildSrc/src/main/groovy/com/uber/okbuck/rule/kotlin/KotlinTestRule.java, libraries/javalibrary/build.gradle
This allows buck test rules to consume the test environment variables set by the various gradle test tasks
=> Add ability to translate test environment

buildSrc/src/main/groovy/com/uber/okbuck/OkBuckGradlePlugin.groovy, buildSrc/src/main/java/com/uber/okbuck/extension/OkBuckExtension.java
Every extra cache requested will create a new configuration "<name>ExtraDepCache" that can be used to fetch and cache dependencies that can be used for tooling purposes etc. during buck
=> Add support for creating extra dependency caches

buildSrc/src/main/groovy/com/uber/okbuck/generator/BuckFileGenerator.groovy, buildSrc/src/main/java/com/uber/okbuck/core/task/OkBuckCleanTask.java
Verified that state files doesn't contain the project entries for intermediate folders with build.gradle which has just some configurations.
=> Only put valid projects in the state file for okbuckclean.

buckw, buildSrc/src/main/groovy/com/uber/okbuck/OkBuckGradlePlugin.groovy, buildSrc/src/main/groovy/com/uber/okbuck/composer/android/KeystoreRuleComposer.groovy, buildSrc/src/main/java/com/uber/okbuck/core/util/LintUtil.java, buildSrc/src/main/java/com/uber/okbuck/extension/WrapperExtension.java, buildSrc/src/main/java/com/uber/okbuck/wrapper/BuckWrapperTask.java, buildSrc/src/main/resources/com/uber/okbuck/core/util/wrapper/BUCKW_TEMPLATE
This PR does a few things:
1) Some of the files/subdirectories of the `.okbuck` directory were being created relative to where `gradlew` was being invoked from, as opposed to the root project dir. This fixes that so that everything under the `.okbuck` directory is created in the right spot.
2) Updates buckw so that `.okbuck` is looked for at `$WORKING_DIR/.okbuck` so that the check for previous successful okbuck runs works appropriately
3) Adds support to buck wrapper generation to ignore specific directories. We were doing this internally and I thought it would be helpful to upstream. This will make sure the watchman queries correctly not attempt to track changes under the `.okbuck` directory.
Our `buckw` internally also looks a bit different because our watchman project root is a folder …
=> Fix .okbuck folder generation

buildSrc/src/main/groovy/com/uber/okbuck/core/model/java/JavaLibTarget.groovy
Verified no buck files changes with same build.gradle configuration.
On overriding test sources to be `[]` `java_test` rule is not generated.
=> Use sourceSets to get sources of JavaTarget

buildSrc/src/main/groovy/com/uber/okbuck/core/dependency/DependencyCache.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/model/base/Scope.groovy
- We do not have sources for these jars and they can take a long time to scan as their parent directory is the entire gradle cache directory
- Reduced the size of the super configuration by not adding project dependencies to it as we iterate all projects anyway
- Simplified source jar copy into dependency cache
- Verified generated buck files are exactly the same before and after
=> Do not scan for sources for gradle api jars

buildSrc/src/main/java/com/uber/okbuck/core/util/RobolectricUtil.java
Add below to DEFS file to support robolectric 3.3.2
```
original_robolectric_test = robolectric_test
def robolectric_test(
name,
force_final_resource_ids=false,
**kwargs
):
original_robolectric_test(
name=name,
force_final_resource_ids=false,
**kwargs
)
```
Buck changes will be merged in - https://github.com/facebook/buck/pull/1305
=> Add support for downloading 22-25 API robolectric runtime dependencies.

buildSrc/src/main/groovy/com/uber/okbuck/OkBuckGradlePlugin.groovy
This prevents the folder from being cleaned every time the project is
evaluated.
=> Move cleaning the .okbuck/gen folder to the first step of setupOkbuck.

app/build.gradle, buildSrc/src/main/groovy/com/uber/okbuck/rule/android/AndroidResourceRule.groovy, libraries/emptyResourceLibrary/build.gradle, libraries/emptyResourceLibrary/src/main/AndroidManifest.xml, libraries/emptyResourceLibrary/src/main/java/com/uber/okbuck/library/empty/resources/Test.java, settings.gradle
This ensures that an R file is created for that module even if there are
no resources. Gradle always generates an R file for each module even if
there are no resources.
=> Add empty resource rule if using resource union.

buildSrc/src/main/groovy/com/uber/okbuck/composer/base/BuckRuleComposer.java, buildSrc/src/main/java/com/uber/okbuck/core/task/OkBuckCleanTask.java, buildSrc/src/main/java/com/uber/okbuck/core/util/FileUtil.java, buildSrc/src/main/java/com/uber/okbuck/core/util/KotlinUtil.java, buildSrc/src/main/java/com/uber/okbuck/core/util/LintUtil.java, buildSrc/src/main/java/com/uber/okbuck/core/util/ProguardUtil.java, buildSrc/src/main/java/com/uber/okbuck/wrapper/BuckWrapperTask.java
The overhead of creating threads for very small tasks might not be
faster than performing the same tasks serially.
I ran a benchmark using this commit against our repo. I killed the
gradle daemon and then ran the okbuck task 3 times.
Before: using parallel()
20.353 secs
6.644 secs
5.89 secs
After: using stream()
18.539 secs
6.316 secs
5.613 secs
The results were quite similar with and without parallel stream. I'm
wondering if there is any noticeable difference with even larger projects.
=> Use stream instead of parallelStream

build.gradle, buildSrc/build.gradle, buildSrc/src/main/groovy/com/uber/okbuck/core/dependency/DependencyCache.groovy, buildSrc/src/main/java/com/uber/okbuck/extension/OkBuckExtension.java, gradle/wrapper/gradle-wrapper.properties, libraries/groovylibrary/build.gradle
This makes it safer for the sake of hermetic builds by surfacing any dynamically versioned dependencies to users
- By default a warning is printed, but it can be made an error by setting `failOnChangingDependencies` in the `okbuck` extension. This behavior will be made to always error on a subsequent release
- Also updated gradle to latest
=> Do not allow snapshot/dynamic dependencies in okbuck

buildSrc/src/main/groovy/com/uber/okbuck/core/model/android/AndroidTarget.groovy
okbuck currently replaces whole <uses-sdk> tag and overrides potential tools:overrideLibrary
=> Preserve tools:overrideLibrary in <uses-sdk>

buildSrc/src/main/groovy/com/uber/okbuck/core/model/android/AndroidTarget.groovy
In the below example, we would expect the final value to be false, but instead it is true.
```
android {
defaultConfig {
buildConfigField "boolean", "VALUE", "true"
}
buildTypes {
debug {
buildConfigField "boolean", "VALUE", "false"
}
}
}
```
With the order switched, it uses the expected value of false instead of true. In Gradle, the result is always false. Gradle prefers to use the build type value over the default.
=> Switch the ordering of build config fields.

buildSrc/src/main/java/com/uber/okbuck/core/task/OkBuckTask.java, buildSrc/src/main/java/com/uber/okbuck/extension/OkBuckExtension.java, buildSrc/src/main/resources/com/uber/okbuck/core/util/defs/OKBUCK_DEFS_TEMPLATE
This can speedup builds by excluding resource configs that are not usually used for debugging. This is similar to the gradle provided option `resConfigs`
https://developer.android.com/studio/build/shrink-code.html#unused-alt-resources
=> Add option to exclude some resources from aapt

buildSrc/src/main/java/com/uber/okbuck/core/task/OkBuckTask.java, buildSrc/src/main/java/com/uber/okbuck/core/util/KotlinUtil.java
Previously we should only check if a module was a kotlin module which
didn't account for kotlin-android modules.
=> Setup Kotlin home whenever the kotlin gradle plugin is on the classpath.

buildSrc/src/main/java/com/uber/okbuck/core/util/TransformUtil.java, buildSrc/src/main/resources/com/uber/okbuck/core/util/transform/BUCK_FILE
This allows transforms written as part of buildSrc or as another project to be utilized as a dependency like
```
dependencies {
transform project(":transform")
}
```
=> Allow transform config to accept project dependencies

buckw, buildSrc/src/main/resources/com/uber/okbuck/core/util/wrapper/BUCKW_TEMPLATE
The IntellIj plugin attempts to run buck tests from within the module
where the test exists which causes the buck wrapper to fail locate the
gradle wrapper. Code taken from:
https://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within/246128#246128
=> Set WORKING_DIR to the location of the buck wrapper.

buckw, buildSrc/src/main/resources/com/uber/okbuck/core/util/wrapper/BUCKW_TEMPLATE
We shouldn't need to run the okbuck task if all we want to do is run `--help` on a buck command.
=> Skip OkBuck if we just want to run buck options.

buildSrc/src/main/groovy/com/uber/okbuck/OkBuckGradlePlugin.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/dependency/DependencyCache.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/model/base/Scope.groovy, buildSrc/src/main/java/com/uber/okbuck/core/dependency/ExternalDependency.java, buildSrc/src/main/java/com/uber/okbuck/core/util/ProjectUtil.java, dependencies.gradle
This enhances the approach detailed in https://github.com/uber/okbuck/wiki/Known-caveats#dependency-conflicts by providing an alternative way to force dependencies across all sub projects. This can be beneficial as gradle performance starts to degrade with many dependency substitution rules.
With the new approach, consumers can set forced versions of dependencies via
```
dependencies {
forcedOkbuck "com.foo:bar:1.0.0"
}
```
To force all sub projects to use `1.0.0` of `com.foo:bar` regardless of what they pull in transitively
=> Add alternative approach to deal with dependency conflicts in android apps

buildSrc/src/main/groovy/com/uber/okbuck/core/dependency/DependencyCache.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/model/base/Store.java, buildSrc/src/main/java/com/uber/okbuck/core/util/ProguardUtil.java, buildSrc/src/main/java/com/uber/okbuck/core/util/RobolectricUtil.java
This moves the link creation step towards the finalization of the Dependency Cache's cleanup phase. Avoids a bunch of extra i/o and removes unnecessary thread safe collections to improve performance.
Also Fixes #497
=> Create dependency cache symlinks during cleanup phase

.travis.yml, buildSrc/src/main/groovy/com/uber/okbuck/composer/android/LintRuleComposer.groovy, buildSrc/src/main/groovy/com/uber/okbuck/composer/base/BuckRuleComposer.java
When running the lint cli on large apps, the transitive classpath passed into the --libraries option can get quite big and hit OS limits like MAX_ARG_STRLEN/ARG_MAX etc. This provides a workaround in okbuck till the issue can be fixed in lint by adding support for classpath argument files in https://issuetracker.google.com/issues/64683008
=> Modify lint to not hit os limits of maximum argument length

buildSrc/src/main/java/com/uber/okbuck/core/util/RobolectricUtil.java
`o-preview-4-robolectric-0` appears to be the most recent version of `android-all`. Not sure if we want to wait for them to release 8.0 but this would at least add support for those beginning to target  API 26.
=> Add Robolectric support for API 26

buildSrc/build.gradle, buildSrc/src/main/groovy/com/uber/okbuck/rule/base/GenRule.groovy, buildSrc/src/main/java/com/uber/okbuck/rule/base/Rule.java, buildSrc/src/main/java/com/uber/okbuck/rule/base/RuleTemplate.java, buildSrc/src/main/rocker/template/base/BuckRule.rocker.raw, buildSrc/src/main/rocker/template/base/GenRule.rocker.raw, dependencies.gradle
Ref #509
This adds support for writing buck rules based on the https://github.com/fizzed/rocker template engine
This allows for modifying templates in a more simple way and comes with lot of performance benefits as the templates are now precompiled to java code. This is going to allow incremental execution of okbuck tasks by outputting each rule to an intermediate file for later merging.
=> Begin migrating buck file generation to template engine

buildSrc/src/main/rocker/com/uber/okbuck/template/config/BuckConfig.rocker.raw
Otherwise aliases generated in `.buckconfig.local` don't work :)
=> Remove ',' after alias value in buckconfig template.

buildSrc/src/main/rocker/com/uber/okbuck/template/android/AndroidBinaryRule.rocker.raw, buildSrc/src/main/rocker/com/uber/okbuck/template/android/AndroidRule.rocker.raw, buildSrc/src/main/rocker/com/uber/okbuck/template/android/BuildConfigRule.rocker.raw, buildSrc/src/main/rocker/com/uber/okbuck/template/android/GenAidlRule.rocker.raw, buildSrc/src/main/rocker/com/uber/okbuck/template/android/LintRule.rocker.raw, buildSrc/src/main/rocker/com/uber/okbuck/template/android/ResourceRule.rocker.raw, buildSrc/src/main/rocker/com/uber/okbuck/template/base/BuckRule.rocker.raw, buildSrc/src/main/rocker/com/uber/okbuck/template/base/GenRule.rocker.raw, buildSrc/src/main/rocker/com/uber/okbuck/template/core/Rule.java, buildSrc/src/main/rocker/com/uber/okbuck/template/java/JavaBinaryRule.rocker.raw, buildSrc/src/main/rocker/com/uber/okbuck/template/java/JavaRule.rocker.raw
The order of deps (i.e classpath) matter for the cache keys of buck. This restores the old behavior of sorting deps entries
=> Sort deps in generated BUCK files

buildSrc/src/main/rocker/com/uber/okbuck/template/config/TransformBuckFile.rocker.raw
This check was preventing okbuck_transform.jar from depending on all of the cached jar files. We want to add the jar dependencies regardless of whether targetDeps is valid or not.
=> Remove target validity check in TransformBuckFile.rocker.raw

buildSrc/src/main/groovy/com/uber/okbuck/composer/android/LintRuleComposer.groovy, dependencies.gradle, libraries/customLintLibrary/build.gradle
Updates custom lint check module to have lint and lint-api as compileOnly and moves custom lint jars from primary to secondary classpath after [this discussion](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/lint-dev/J6XVMjGM8Hs/vAaK2LXYAAAJ). The primary will now only contain the okbuck_lint fat jar while the secondary classpath will have third party lint checks like timber plus the bin_main targets of custom lint check modules.
Addresses #529
=> Add support for Lint 26.0.0-beta7

buildSrc/src/main/java/com/uber/okbuck/core/util/ProjectUtil.java
When using Gradle buildscript dependencies as jar files, OkBuck would throw a 
```
Caused by: java.lang.ClassCastException: org.gradle.internal.component.local.model.OpaqueComponentArtifactIdentifier cannot be cast to org.gradle.api.artifacts.component.ModuleComponentIdentifier
at com.uber.okbuck.core.util.ProjectUtil.lambda$findVersionInClasspath$0(ProjectUtil.java:83)
at com.uber.okbuck.core.util.ProjectUtil.findVersionInClasspath(ProjectUtil.java:87)
at com.uber.okbuck.core.util.LintUtil.getDefaultLintVersion(LintUtil.java:31)
at com.uber.okbuck.extension.LintExtension.<init>(LintExtension.java:28)
at com.uber.okbuck.extension.LintExtension_Decorated.<init>(Unknown Source)
at org.gradle.internal.reflect.DirectInstantiator.newInstance(DirectInstantiator.java:51)
... 134 more
```
This …
=> Fix OkBuck exception when buildscript dependency is Jar

buildSrc/src/main/groovy/com/uber/okbuck/composer/android/AndroidLibraryRuleComposer.groovy, buildSrc/src/main/groovy/com/uber/okbuck/composer/android/AndroidTestRuleComposer.groovy, buildSrc/src/main/groovy/com/uber/okbuck/composer/android/LintRuleComposer.groovy, buildSrc/src/main/groovy/com/uber/okbuck/generator/BuckFileGenerator.groovy
Looking at the source of the android gradle plugin, it seems like the merged manifest is not used for lint or for running unit tests. Mimic'ing the same behavior
=> Do not use merged manifest for lint and unit tests

buildSrc/src/main/java/com/uber/okbuck/core/util/KotlinUtil.java
`<kotlin_home>/libexec/lib` is where it expects library jars to be placed.
Without the proper placement, any compiler error would result in warnings at the top of the output:
```
kotlinc
stderr: warning: unable to find kotlin-stdlib.jar in the Kotlin home directory. Pass either '-no-stdlib' to prevent adding it to the classpath, or the correct '-kotlin-home'
warning: unable to find kotlin-script-runtime.jar in the Kotlin home directory. Pass either '-no-stdlib' to prevent adding it to the classpath, or the correct '-kotlin-home'
warning: unable to find kotlin-reflect.jar in the Kotlin home directory. Pass either '-no-reflect' or '-no-stdlib' to prevent adding it to the classpath, or the correct '-kotlin-home'
```
These can be rather confusing when diagnosing the real cause of an issue. …
=> Structure OkBuck's KOTLIN_HOME directory in the format it expects

build.gradle, buildSrc/src/main/groovy/com/uber/okbuck/core/model/android/AndroidAppTarget.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/model/android/AndroidLibTarget.groovy, buildSrc/src/main/groovy/com/uber/okbuck/generator/BuckFileGenerator.groovy, buildSrc/src/main/java/com/uber/okbuck/extension/OkBuckExtension.java, dummylibrary/build.gradle, dummylibrary/src/com/uber/okbuck/example/dummylibrary/DummyAndroidClass.java, libraries/common/build.gradle, libraries/common/src/main/java/com/uber/okbuck/example/common/Calc.java
Library build configs are typically not useful as apps tend to override things like version/debug mode etc. This adds an option to turn off library build configs entirely to save time during builds
=> Add option to disable generating build config rules for library modules

another-app/build.gradle, another-app/proguard-android.txt, buildSrc/src/main/groovy/com/uber/okbuck/composer/android/AndroidLibraryRuleComposer.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/dependency/DependencyCache.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/model/android/AndroidAppTarget.groovy, buildSrc/src/main/groovy/com/uber/okbuck/core/model/android/AndroidLibTarget.groovy, buildSrc/src/main/rocker/com/uber/okbuck/template/android/AndroidRule.rocker.raw, libraries/parcelable/build.gradle, libraries/parcelable/proguard.txt
We do not need to merge proguard files from aars because buck supports this natively already
Built test app with consumer proguard rules and observed that the keep rules were respected via classy shark
=> Switch to using inbuilt consumer proguard file support in buck

buildSrc/src/main/resources/com/uber/okbuck/core/util/gen/BUCK_FILE, buildSrc/src/main/resources/com/uber/okbuck/core/util/lint/BUCK_FILE, buildSrc/src/main/rocker/com/uber/okbuck/template/config/TransformBuckFile.rocker.raw
- This works around the behavior change in https://github.com/facebook/buck/issues/1630
- Okbuck also does not need a strict copy anywhere it uses `export_file` so this is lot better for build performance in general
=> Always use export_file in reference mode in okbuck

.travis.yml, app/src/androidTest/java/com/uber/okbuck/example/test/MainActivityTest.java, buildSrc/src/main/rocker/com/uber/okbuck/template/android/InstrumentationApkRule.rocker.raw
PR #551 didn't enable d8 dexer for instrumentation apk which causes instrumentation apk build failure if user uses Java 8 lang features.
=> Use d8 dexer for instrumentation apk.

build.gradle, buildSrc/src/main/groovy/com/uber/okbuck/core/model/java/JavaTarget.groovy, dependencies.gradle, libraries/javalibrary/build.gradle
Before this change, okbuck would pickup APs from the `compileOnly` configuration only that can cause processor dependencies to pollute the classpath of java projects (unlike android projects that separate the `provided` and `annotationProcessor` configurations). This would cause discrepancies in the buck and gradle builds.
This changes the behavior of okbuck to only pickup processors from the `apt`/`testApt` configurations for java projects. Android project behavior is unchanged.
You may use plugins like https://github.com/tbroyer/gradle-apt-plugin to easily gain access to the `apt` configurations for java projects.
=> Only use apt configuration for java project annotation processors

buildSrc/src/main/java/com/uber/okbuck/core/util/RobolectricUtil.java, dependencies.gradle
- Removes unused runtime deps
- Updates runtime deps to latest
- Backwards incompatible with older robolectric versions
=> Update to support robolectric 3.6

buildSrc/src/main/groovy/com/uber/okbuck/composer/android/ExopackageAndroidLibraryRuleComposer.groovy
Generated app_lib_exo rule, of type android_library, doesn't support specifying annotation processor deps. While this shouldn't be needed normally, it prevents to apply any plugin through extra params or annotation processor to the exo module.
=> Added missing dependencies and annotation processor dependencies to exo app lib rule

buildSrc/src/main/groovy/com/uber/okbuck/core/dependency/DependencyCache.groovy
Changing versions like `+` or `SNAPSHOT` are always at the end of the version string. This makes the version check less agressive
Fixes #576
=> Make changing versions dependency check less aggressive

another-app/build.gradle, buildSrc/src/main/groovy/com/uber/okbuck/core/model/android/AndroidAppTarget.groovy
If more than one proguard file is detected, fail the build because
okbuck will not use the other files
=> Add better error messages for multiple proguard files

.watchmanconfig, buildSrc/src/main/resources/com/uber/okbuck/core/util/wrapper/WATCHMAN_CONFIG
The comma at the end was causing watchman to silently ignore the config.
=> Fix watchman config default ignores.

buildSrc/src/main/groovy/com/uber/okbuck/OkBuckGradlePlugin.groovy
Was trying to figure out why am I getting this error when I'm trying to use custom Buck binary as recommended in [changelog for 0.32.2](https://github.com/uber/okbuck/releases/tag/v0.32.2):
```console
Could not find method buckBinary() for arguments [our.custom.buck:buck:someversion@pex] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```
Turned out changelog says to use `buckBinary` configuration while actual configuration name is `buck_binary` :trollface: 
Alternative fix would be to update changelog, but Gradle typically uses CamelCase for configuration names.
=> Fix buckBinary configuration name: _ to CamelCase.

build.gradle, buildSrc/src/main/groovy/com/uber/okbuck/OkBuckGradlePlugin.groovy, buildSrc/src/main/groovy/com/uber/okbuck/composer/base/BuckRuleComposer.java, buildSrc/src/main/java/com/uber/okbuck/core/task/OkBuckTask.java, buildSrc/src/main/java/com/uber/okbuck/extension/ExperimentalExtension.java, buildSrc/src/main/rocker/com/uber/okbuck/template/config/BuckDefs.rocker.raw
Running android lint on a target only needs dependent libraries class-abi,
i.e doesn’t need to rerun lint if there are no api changes in the dependent
libraries.
Using classpath_abi returns class-abi jars of the dependencies instead of
the class jar. (Buck pr - https://github.com/facebook/buck/pull/1780)
Usage: $(@classpath_abi :<target_path>)
To enable using classpath_abi, add the experimental extension
```
okbuck {
experimental {
lintWithClasspathAbi = true
}
}
```
=> Use classpath_abi macro instead of classpath in lint genrule.

buildSrc/src/main/java/com/uber/okbuck/core/dependency/ExternalDependency.java, buildSrc/src/main/java/com/uber/okbuck/core/model/base/Scope.java, buildSrc/src/main/java/com/uber/okbuck/core/model/base/TargetCache.java
Prevents adding annotation processor classes from transitive dependencies.
=> Only get annotation processor classes from the configuration’s first level dependencies.

buildSrc/src/main/java/com/uber/okbuck/core/dependency/DependencyUtils.java
- Use baseFileName to get the substring so it doesn’t include the extension.
- Return version if the filename doesn’t have a version.
=> Fix module version computation

buildSrc/src/main/java/com/uber/okbuck/extension/OkBuckExtension.java
This is to prevent NPE when the extensions are not specified in okbuck extension.
Resolves: https://github.com/uber/okbuck/issues/633
=> Initialize IntelliJ & Experimental extensions with default ones

buildSrc/src/main/groovy/com/uber/okbuck/core/dependency/DependencyCache.groovy
Commit https://github.com/uber/okbuck/commit/6804eae935b01c359d2b9c09af4fff6d7666b778 broke fetching deps sources for IntelliJ project model
=> Fix fetchSources for IntelliJ project.

buildSrc/src/main/groovy/com/uber/okbuck/core/model/base/AnnotationProcessorCache.java
AnnotationProcessorCache is being called by multiple tasks on different 
threads, changing dependencyToScopeMap to ConcurrentHashMap should prevent
any race condition.
=> Use ConcurrentHashMap in annotation processor cache to prevent any race condition

buildSrc/src/main/groovy/com/uber/okbuck/core/model/base/AnnotationProcessorCache.java, buildSrc/src/main/java/com/uber/okbuck/core/model/base/Scope.java
Compute MD5 hash of the appended UID and add it to the auto value dependency 
to prevent them from being too long.
Previous:
```
java_annotation_processor(
name = 'processor_com.google.auto.value-auto-value-1.6-com.google.auto.value-auto-value-annotations-1.6-com.ryanharter.auto.value-auto-value-gson-0.7.0',
processor_classes = [
'com.google.auto.value.extension.memoized.processor.MemoizedValidator',
'com.google.auto.value.processor.AutoAnnotationProcessor',
'com.google.auto.value.processor.AutoOneOfProcessor',
```
New:
```
java_annotation_processor(
name = 'processor_com.google.auto.value-auto-value-1.6__525046afa7fcbcf1dcd36f17908d83ff',
processor_classes = [
'com.google.auto.value.extension.memoized.processor.MemoizedValidator', …
```
=> Keep annotation processor plugins rule name’s length small

buildSrc/src/main/rocker/com/uber/okbuck/template/config/ScalaBuckFile.rocker.raw
This is necessary to prevent Buck from building scala into published libraries.
=> Add maven coords to scala_library.

buckw, buildSrc/src/main/rocker/com/uber/okbuck/template/config/BuckWrapper.rocker.raw
The current check passed for modules that contains -h in their name, not only the flag -h. 
Fixes #676
=> fixing skip check bug

buildSrc/src/main/java/com/uber/okbuck/core/dependency/ExternalDependency.java
Previously okBuck relied on version to identify 2 unique dependencies (and by the moment it got to okbuck, atrifact had chance to have 2 separate verisons only if because of classifiers)
after pull/678 these artifacts became equal, this producing false uniqueness behavior.
=> Fixing bug introduced by pull/678

buildSrc/src/main/java/com/uber/okbuck/core/model/android/AndroidTarget.java, dependencies.gradle, gradle/wrapper/gradle-wrapper.properties, transform-cli/src/main/java/com/uber/okbuck/transform/FileUtil.java
- Upgrade Gradle to 4.8.1
- Upgrade AGP to 3.2.0-beta01 and change breaking api (https://issuetracker.google.com/issues/76031225)
- According to Files api docs, the streams returned by Files.walk and Files.lines must be properly closed to release the resources. This plugs a few file leaks in okbuck
- Fixes #686
=> Upgrade Gradle and AGP versions

buildSrc/src/main/java/com/uber/okbuck/core/model/android/AndroidAppTarget.java
```
Caused by: java.lang.NullPointerException
at com.uber.okbuck.core.model.android.AndroidAppTarget.<init>(AndroidAppTarget.java:52)
at com.uber.okbuck.core.model.android.AndroidAppTarget.<init>(AndroidAppTarget.java:96)
at com.uber.okbuck.core.model.base.TargetCache.getTargets(TargetCache.java:38)
at com.uber.okbuck.OkBuckGradlePlugin.lambda$null$4(OkBuckGradlePlugin.java:143)
at com.uber.okbuck.OkBuckGradlePlugin.lambda$null$6(OkBuckGradlePlugin.java:143)
at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:794)
at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:761)
at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
at …
```
=> Fix a NullPointerException happening on the use of ndkCompile.

.circleci/config.yml, buildSrc/src/main/java/com/uber/okbuck/core/dependency/DependencyCache.java, buildSrc/src/main/java/com/uber/okbuck/core/util/FileUtil.java
Some artifacts like `com.google.code.findbugs:annotations` and `com.google.code.findbugs:jsr305` have `-sources` jar artifacts available on mavencentral, but they are not actual source jars which cause intellij to fail with warning logs like
```
WARN - penapi.vfs.impl.jar.JarHandler - error in opening zip file: .okbuck/cache/com.google.code.findbugs--annotations--2.0.1-sources.jar
java.util.zip.ZipException: error in opening zip file
at java.util.zip.ZipFile.open(Native Method)
at java.util.zip.ZipFile.<init>(ZipFile.java:219)
at java.util.zip.ZipFile.<init>(ZipFile.java:149)
at java.util.zip.ZipFile.<init>(ZipFile.java:120)
at com.intellij.openapi.vfs.impl.ZipHandler$1.createAccessor(ZipHandler.java:45)
at com.intellij.openapi.vfs.impl.ZipHandler$1.createAccessor(ZipHandler.java:39)
at …
```
=> Do not pickup source jars which are not actually zip files

buildSrc/src/main/java/com/uber/okbuck/core/task/OkBuckTask.java, buildSrc/src/main/java/com/uber/okbuck/extension/LintExtension.java, buildSrc/src/main/rocker/com/uber/okbuck/template/config/BuckDefs.rocker.raw
This lets us exclude Nullaway's jar infer model jars for example via a regex
=> Add ability to filter entries out of android lint classpath

buckw, buildSrc/src/main/java/com/uber/okbuck/OkBuckGradlePlugin.java, buildSrc/src/main/java/com/uber/okbuck/composer/jvm/JvmBuckRuleComposer.java, buildSrc/src/main/java/com/uber/okbuck/core/manager/BuckManager.java, buildSrc/src/main/java/com/uber/okbuck/core/manager/GroovyManager.java, buildSrc/src/main/java/com/uber/okbuck/core/manager/KotlinManager.java, buildSrc/src/main/java/com/uber/okbuck/core/manager/LintManager.java, buildSrc/src/main/java/com/uber/okbuck/core/manager/ManifestMergerManager.java, buildSrc/src/main/java/com/uber/okbuck/core/manager/RobolectricManager.java, buildSrc/src/main/java/com/uber/okbuck/core/manager/ScalaManager.java, buildSrc/src/main/java/com/uber/okbuck/core/manager/TransformManager.java, buildSrc/src/main/java/com/uber/okbuck/core/task/OkBuckCleanTask.java, buildSrc/src/main/java/com/uber/okbuck/core/util/D8Util.java, buildSrc/src/main/rocker/com/uber/okbuck/template/config/BuckDefs.rocker.raw, buildSrc/src/main/rocker/com/uber/okbuck/template/config/BuckWrapper.rocker.raw, transform-cli/src/main/java/com/uber/okbuck/transform/JarsTransformOutputProvider.java, transform-cli/src/test/java/com/uber/okbuck/transform/JarsTransformOutputProviderTest.java
- Move `.okbuck/cache` to `.okbuck/workspace`
- Delete old `.okbuck/cache` directory to avoid old buck rules from hanging around
- Prepare to move `3rdparty` inside `.okbuck` by default
=> Move okbuck cache to workspace

dependencies.gradle
- Update AGP to 3.2.0
- Update build tools to 28.0.3
- Update support to 28.0.0
=> Update AGP, support lib and build tools to latest

app/src/main/java/com/uber/okbuck/example/MainActivity.java, build.gradle, buildSrc/src/main/java/com/uber/okbuck/composer/android/AndroidBuckRuleComposer.java, buildSrc/src/main/java/com/uber/okbuck/composer/android/AndroidResourceRuleComposer.java, buildSrc/src/main/java/com/uber/okbuck/composer/android/ManifestRuleComposer.java, buildSrc/src/main/java/com/uber/okbuck/core/model/android/AndroidTarget.java, buildSrc/src/main/java/com/uber/okbuck/extension/OkBuckExtension.java, buildSrc/src/main/java/com/uber/okbuck/generator/BuckFileGenerator.java, buildSrc/src/main/rocker/com/uber/okbuck/template/android/ManifestRule.rocker.raw, buildSrc/src/main/rocker/com/uber/okbuck/template/config/BuckDefs.rocker.raw
- Change `resourceUnion` extension option to `resourceUnionPackage`
- Use resource union package when available for library manifests (IDE support etc.)
- Make sure binaries still use the final application id
- Cleanup some okbuck defs
=> Add ability to configure buck's resource_union package name

buildSrc/src/main/java/com/uber/okbuck/core/manager/RobolectricManager.java
**Description**: Robolectric 4.0-alpha-3 is their first release with support for API 28, and it requires the SDK dependency `android-all-9-robolectric-4799589` as specified in their [org.robolectric.internal.SdConfig](https://github.com/robolectric/robolectric/blob/4fbb097ff619fab3ea405e1a1ce7b04a83dfe836/robolectric/src/main/java/org/robolectric/internal/SdkConfig.java#L31).
Currently okbuck specifies as sdk dependency for API 28 `android-all-P-robolectric-4651975`.
This means that you cannot use okbuck with an API 28 with robolectric, as robolectric expects `android-all-9-robolectric-4799589` but okbuck only offers `android-all-P-robolectric-4651975`.
=> Add support for API 28 robolectric dependencies expected by robolectric 4.0-alpha-3

buildSrc/src/main/rocker/com/uber/okbuck/template/android/ManifestRule.rocker.raw, buildSrc/src/main/rocker/com/uber/okbuck/template/config/BuckDefs.rocker.raw
- `--debuggable false` is being passed correctly which was always `true` since it was a string. 
Before:
```
okbuck_manifest(
name = 'manifest_lib_debug',
main_manifest = 'src/main/AndroidManifest.xml',
min_sdk = '24',
target_sdk = '27',
package = 'com.uber',
version_code = '1',
version_name = '0.2.0',
debuggable = ‘false’,
)
```
After:
```
okbuck_manifest(
name = 'manifest_lib_debug',
main_manifest = 'src/main/AndroidManifest.xml',
min_sdk = '24',
target_sdk = '27',
package = 'com.uber',
version_code = '1',
version_name = '0.2.0',
debuggable = False,
)
```
```
"cmd" : "java -jar -Xmx256m $(location //.okbuck/workspace/manifest-merger:okbuck_manifest_merger) --main $SRCDIR/src/main/AndroidManifest.xml --overlays $SRCDIR/src/release/AndroidManifest.xml --property MIN_SDK_VERSION=15 …
```
=> Set debuggable to boolean instead of string for it to be computed correctly.

app/src/debug/AndroidManifest.xml, buildSrc/src/main/rocker/com/uber/okbuck/template/config/BuckDefs.rocker.raw
This fixes following error thrown at Buck build time if multiple values were passed after `--overlays` option:
```console
Build failed: Command failed with exit code 1.
stderr: Error: Command switch /Users/user/projects/project/buck-out/gen/project/manifest_lib_devDebug/AndroidManifest.xml has no value associated
When running <(cd buck-out/gen/project/manifest_lib_devDebug__srcs && OUT=/Users/user/projects/project/buck-out/gen/project/manifest_lib_devDebug/AndroidManifest.xml SRCDIR=/Users/user/projects/project/buck-out/gen/project/manifest_lib_devDebug__srcs /bin/bash -e /Users/user/projects/project/buck-out/tmp/genrule-1107998254956004441.sh)>.
When building rule //project/manifest_lib_devDebug.
```
[ManifestMergerCli is capable](https://github.com/uber/okbuck/blob/v0.43.0/manifest-merge …
=> Fix manifest-merger --overlays

buildSrc/src/main/java/com/uber/okbuck/core/manager/JetifierManager.java
**Description**: `android.useAndroidX` is meant for code gen tools to generate androidx symbols and is not directly related to jetifier
**Related issue(s)**: N/A
=> Gate jetifier only on android.enableJetifier

buildSrc/src/main/java/com/uber/okbuck/OkBuckGradlePlugin.java, buildSrc/src/main/java/com/uber/okbuck/extension/OkBuckExtension.java, buildSrc/src/main/java/com/uber/okbuck/extension/RuleOverridesExtension.java, buildSrc/src/main/java/com/uber/okbuck/generator/BuckFileGenerator.java, buildSrc/src/main/rocker/com/uber/okbuck/template/core/Rule.java
Now instead of having to define java_library in DEFS one can tell okBuck to load and use my_java_library in //defs/my_defs.bzl like:
```
okbuck {
ruleOverrides {
override {
nativeRuleName = "java_library"
importLocation = "//defs/my_defs.bzl"
newRuleName = "my_java_library"
}
}
}
```
with this config specified, generates files look like this:
```
load('//defs/my_defs.bzl', 'my_java_library')
my_java_library(
...
```
=> Added option to okBuck to configure rule overrides compatible with skylark

build.gradle, buildSrc/src/main/java/com/uber/okbuck/composer/java/PrebuiltRuleComposer.java, buildSrc/src/main/java/com/uber/okbuck/core/dependency/DependencyCache.java, buildSrc/src/main/java/com/uber/okbuck/core/dependency/DependencyUtils.java, buildSrc/src/main/java/com/uber/okbuck/core/dependency/ExternalDependency.java, buildSrc/src/main/java/com/uber/okbuck/core/manager/DependencyManager.java, buildSrc/src/main/java/com/uber/okbuck/core/model/base/Scope.java, buildSrc/src/main/java/com/uber/okbuck/core/task/OkBuckTask.java, buildSrc/src/main/java/com/uber/okbuck/core/util/ProguardUtil.java, buildSrc/src/main/java/com/uber/okbuck/extension/JetifierExtension.java, buildSrc/src/main/java/com/uber/okbuck/extension/OkBuckExtension.java, buildSrc/src/main/java/com/uber/okbuck/extension/RuleOverridesExtension.java, buildSrc/src/main/rocker/com/uber/okbuck/template/config/BuckDefs.rocker.raw, buildSrc/src/main/rocker/com/uber/okbuck/template/java/Prebuilt.rocker.raw
Some jars also depends on old android support packages. So running jetifier on jars is also an important step to fully provide support for jetifier and androidX.
In order to provide that, while still being able to have performatic builds, the need to run jetifier is now calculated per dependency, and not settled entirely for a given packaging type (as it was with aars before)
Main changes, then, are:
* Enable jetifier is now calculated per dependency
* Make generated defs clearer for when jetifier is not enabled in project
* Jetifier by default will be enabled only for all types of external dependencies (jars and aars) packagings. But one can optOut (from jars) by configuring `aarOnly` on the jetifier extension
* It's now also possible, for both jars and aars, to provide a list of regexes …
=> Enable jetifier for jars

buildSrc/src/main/java/com/uber/okbuck/OkBuckGradlePlugin.java, buildSrc/src/main/java/com/uber/okbuck/core/model/base/Scope.java, buildSrc/src/main/java/com/uber/okbuck/core/util/ProjectUtil.java
Scope cache is only required during the lifecycle of the okbuck task. 
Running `jcmd <pid> GC.run` on the process lowers down the memory footprint significantly which was not happening before.
=> Cache scope as an extra property to project instead of keeping it on the plugin object.

buildSrc/build.gradle, buildSrc/src/main/java/com/uber/okbuck/OkBuckGradlePlugin.java, buildSrc/src/main/java/com/uber/okbuck/core/manager/LintManager.java, buildSrc/src/main/java/com/uber/okbuck/core/model/base/Scope.java, buildSrc/src/main/java/com/uber/okbuck/core/model/base/TargetCache.java, buildSrc/src/main/java/com/uber/okbuck/core/util/ProjectCache.java, buildSrc/src/main/java/com/uber/okbuck/core/util/ProjectUtil.java, buildSrc/src/main/java/com/uber/okbuck/generator/BuckFileGenerator.java
- Move ScopeCache & TargetCache into ProjectCache class
- Lazy initialize targets of a project
- Reset rootProject's cache extra properties correctly
- Initialize target cache at start of `setupOkbuck` task and reset at end of `rootOkbuckTask`. This can't be done at the local level of a project's okbuck task since the target cache is shared b/w projects.
- Lowers down memory footprint from 1.5 GB to 1GB.
=> Cache TargetCache as an extra property of the project instead of OkBuckGradlePlugin

.circleci/config.yml, buildSrc/src/main/rocker/com/uber/okbuck/template/config/BuckConfig.rocker.raw, dependencies.gradle
- `target` is not needed in `kotlin_home` 
- Add an option to invalidate gradle cache
- Don't build with `-v 0`
=> Remove redundant kotlin_home config param target

buildSrc/src/main/java/com/uber/okbuck/composer/android/AndroidBinaryRuleComposer.java
* Simply adding support to `arm64-v8a` as a recognizable attribute for ABI in okbuck
Pulling in the `ARM64` enum from - https://github.com/facebook/buck/blob/a6c7d7391a7a8e575c6372cac6690a240b5907ea/src/com/facebook/buck/android/toolchain/ndk/TargetCpuType.java
=> Adding arm64-v8a as a supported ABI to okbuck

buildSrc/src/main/java/com/uber/okbuck/core/model/android/AndroidAppTarget.java
Demo diff for https://github.com/uber/okbuck/issues/828. It first checks whether `multiDexEnabled` is defined in `buildType`. If not present, then check  in `defaultConfig`.
=> [Demo diff] Added support for reading multiDexEnabled from build type based config

another-app/build.gradle, buildSrc/build.gradle, buildSrc/src/main/java/com/uber/okbuck/composer/android/AndroidLibraryRuleComposer.java, buildSrc/src/main/java/com/uber/okbuck/composer/android/AndroidResourceRuleComposer.java, buildSrc/src/main/java/com/uber/okbuck/composer/android/AndroidTestRuleComposer.java, buildSrc/src/main/java/com/uber/okbuck/composer/jvm/JvmBuckRuleComposer.java, buildSrc/src/main/java/com/uber/okbuck/composer/jvm/JvmLibraryRuleComposer.java, buildSrc/src/main/java/com/uber/okbuck/composer/jvm/JvmTestRuleComposer.java, buildSrc/src/main/java/com/uber/okbuck/core/dependency/DependencyCache.java, buildSrc/src/main/java/com/uber/okbuck/core/dependency/DependencyFactory.java, buildSrc/src/main/java/com/uber/okbuck/core/dependency/DependencyUtils.java, buildSrc/src/main/java/com/uber/okbuck/core/model/android/AndroidAppTarget.java, buildSrc/src/main/java/com/uber/okbuck/core/model/android/AndroidTarget.java, buildSrc/src/main/java/com/uber/okbuck/core/model/android/ExoPackageScope.java, buildSrc/src/main/java/com/uber/okbuck/core/model/base/Scope.java, buildSrc/src/main/java/com/uber/okbuck/core/model/jvm/JvmTarget.java, buildSrc/src/main/rocker/com/uber/okbuck/template/android/AndroidRule.rocker.raw, buildSrc/src/main/rocker/com/uber/okbuck/template/jvm/JvmRule.rocker.raw, libraries/javalibrary/build.gradle
- This adds a preliminary support for external_deps.
- `deps` still contains the transitive api deps — will be cleaned in subsequent pr’s.
- Verified that the exported_deps are being composed correctly for java & android libraries.
=> Add support for composing api deps in external_deps.

build.gradle, buildSrc/src/main/java/com/uber/okbuck/core/dependency/ExternalDependency.java, buildSrc/src/main/java/com/uber/okbuck/core/manager/DependencyManager.java, buildSrc/src/main/java/com/uber/okbuck/extension/ExternalDependenciesExtension.java, buildSrc/src/main/java/com/uber/okbuck/extension/OkBuckExtension.java, buildSrc/src/main/java/com/uber/okbuck/extension/ResolutionAction.java
This allows for only the below resolution actions:
- latest
- all
- single (fails if finds multiple versions)
When using latest or single versionless names will be used for external dependencies.
Can also specify coordinates for deps whose all versions is to be allowed when in latest or single mode. for eg: roblectric runtime deps.
```
externalDependency {
resolutionAction = latest
allowAllVersions = [
"org.robolectric:android-all",
"com.guava:guava",
]
}
```
=> Cleanup versionless resolution actions handling

build.gradle, buildSrc/src/main/java/com/uber/okbuck/composer/android/AndroidBuckRuleComposer.java, buildSrc/src/main/java/com/uber/okbuck/composer/android/AndroidLibraryRuleComposer.java, buildSrc/src/main/java/com/uber/okbuck/composer/android/AndroidResourceRuleComposer.java, buildSrc/src/main/java/com/uber/okbuck/composer/android/ExopackageAndroidLibraryRuleComposer.java, buildSrc/src/main/java/com/uber/okbuck/composer/java/JavaAnnotationProcessorRuleComposer.java, buildSrc/src/main/java/com/uber/okbuck/composer/java/LocalPrebuiltRuleComposer.java, buildSrc/src/main/java/com/uber/okbuck/composer/java/PrebuiltRuleComposer.java, buildSrc/src/main/java/com/uber/okbuck/core/dependency/DependencyCache.java, buildSrc/src/main/java/com/uber/okbuck/core/dependency/DependencyFactory.java, buildSrc/src/main/java/com/uber/okbuck/core/dependency/ExternalDependency.java, buildSrc/src/main/java/com/uber/okbuck/core/manager/DependencyManager.java, buildSrc/src/main/java/com/uber/okbuck/core/model/android/ExoPackageScope.java, buildSrc/src/main/java/com/uber/okbuck/core/model/base/Scope.java, buildSrc/src/main/java/com/uber/okbuck/core/model/jvm/JvmTarget.java, buildSrc/src/main/java/com/uber/okbuck/core/util/ProjectUtil.java, buildSrc/src/main/java/com/uber/okbuck/extension/ExternalDependenciesExtension.java, buildSrc/src/main/rocker/com/uber/okbuck/template/android/ResourceRule.rocker.raw, buildSrc/src/main/rocker/com/uber/okbuck/template/config/OkbuckPrebuilt.rocker.raw, buildSrc/src/main/rocker/com/uber/okbuck/template/java/Prebuilt.rocker.raw, dependencies.gradle, libraries/parcelable/build.gradle, libraries/scalalibrary/build.gradle
To make generated buck files small and less verbose we can use `exported_deps` for api dependencies. deps of prebuilts are exported by default (i.e dependees of a prebuilt will also get prebuilt's dependencies in it's compile classpath). 
To enable this make the below changes in okbuck extension:
```
okbuck {
resolutionAction = "latest"
enableExportedDeps = true
}
}
```
Note: this only works when `resolutionAction` is either `latest` or `single`.
example generated buck files:
```
// in .okbuck/ext/androidx/activity/BUCK
load('//.okbuck/defs:okbuck_prebuilt.bzl', 'okbuck_prebuilt')
okbuck_prebuilt(
name = 'activity.aar',
maven_coords = 'androidx.activity:activity:aar:1.0.0-alpha04',
sha256 = '4a2c0a2e53933075fa6979b8921a8c7047ec60d5e3906d774f77bd598842aad9', …
```
=> Add support for exported_deps for aar & jar prebuilts.

buildSrc/src/main/java/com/uber/okbuck/core/manager/DependencyManager.java, dependencies.gradle
If this happens that means that some deps are being substituted to a project dependency. Hence upon resolving just the external dependencies those substituted external dependencies might not be found in project's resolved dependency list.
=> Throw exception if a dep is not found in resolved dependency list when exported deps is enabled

build.gradle, buildSrc/build.gradle, buildSrc/src/main/java/com/uber/okbuck/OkBuckGradlePlugin.java, buildSrc/src/main/java/com/uber/okbuck/composer/java/JavaAnnotationProcessorRuleComposer.java, buildSrc/src/main/java/com/uber/okbuck/composer/jvm/JvmBuckRuleComposer.java, buildSrc/src/main/java/com/uber/okbuck/core/annotation/AnnotationProcessorCache.java, buildSrc/src/main/java/com/uber/okbuck/core/annotation/JvmPlugin.java, buildSrc/src/main/java/com/uber/okbuck/core/dependency/DependencyCache.java, buildSrc/src/main/java/com/uber/okbuck/core/dependency/ExternalDependency.java, buildSrc/src/main/java/com/uber/okbuck/core/manager/DependencyManager.java, buildSrc/src/main/java/com/uber/okbuck/core/model/base/Scope.java, buildSrc/src/main/java/com/uber/okbuck/core/model/jvm/JvmTarget.java, buildSrc/src/main/java/com/uber/okbuck/extension/ExternalDependenciesExtension.java, dependencies.gradle
- Single processors work as expected.
- autoValue extensions need to pre predefined so that the dependency updater tool can work without having to infer auto value dependencies & its extensions by looking at the project's apt configuration. 
```file=build.gradle
okbuck {
autoValueConfigurations = [
"autoValueAnnotations",
"autoValueGson",
"autoValueParcel",
]
}
}
def autoValueDeps = [deps.apt.autoValue, deps.apt.autoValueAnnotations]
def autoValueGsonDeps = autoValueDeps + [deps.apt.autoValueGson]
def autoValueParcelDeps = autoValueDeps + [deps.apt.autoValueParcel]
afterEvaluate {
dependencies {
toolsExtraDepCache deps.external.saxon
autoValueAnnotations autoValueDeps
autoValueGson autoValueGsonDeps
autoValueParcel autoValueParcelDeps
}
}
``` 
- Auto value …
=>  Compose external dependency processors in external dependency's buck file

buildSrc/src/main/java/com/uber/okbuck/composer/android/AndroidTestRuleComposer.java, buildSrc/src/main/java/com/uber/okbuck/generator/BuckFileGenerator.java, buildSrc/src/main/rocker/com/uber/okbuck/template/config/OkbuckAndroidModules.rocker.raw
Basically:
* res_release should go into the deps of the library and exported_deps of the corresponding resource (if respective src_release is in exported deps)
* res_release should go into the deps of the library and deps of the corresponding resource (if not respective src_release not exported)
This PR fixes the part of having the `res_release` as dep, in case it respective `src` was exported
EDIT
This PR also fixes missing `res` rules as dependencies for test rules (robolectric and instrumentation)
=> Small fix on android module macro

buildSrc/src/main/java/com/uber/okbuck/composer/android/AndroidTestRuleComposer.java, buildSrc/src/main/java/com/uber/okbuck/generator/BuckFileGenerator.java
Reverts adding manifest and/or rules as deps on tests rules; This works, so it's better to leave this way as it's more intuitive to only depend on the actual library rule and not the hidden ones when writing BUCK files manually
=> Partially revert #852

buildSrc/src/main/java/com/uber/okbuck/composer/android/AndroidModuleRuleComposer.java
Similar to https://github.com/uber/okbuck/pull/849, but for kotlin
=> Handle empty lint xml config properly for unified rule

buildSrc/src/main/java/com/uber/okbuck/composer/android/AndroidModuleRuleComposer.java
This adds a small change to https://github.com/uber/okbuck/pull/855
=> Fix typo when handling empty lint xml in pull/855

buildSrc/src/main/java/com/uber/okbuck/core/model/jvm/TestOptions.java, dependencies.gradle, libraries/javalibrary/build.gradle
Verified:
```
env = {
'CACHE_CASSANDRA_CONTACT_POINTS': '[testhost]',
'CACHE_CASSANDRA_PORT': '1234',
'OKBUCK_DATACENTER': 'testdc1',
'OKBUCK_PORT_HTTP': '4321',
'TEST_ENV': 'true',
},
```
=> Ensure that test env dict is printed in sorted manner.

buildSrc/src/main/java/com/uber/okbuck/core/dependency/DependencyUtils.java, buildSrc/src/main/java/com/uber/okbuck/core/manager/DependencyManager.java, buildSrc/src/main/java/com/uber/okbuck/core/model/base/Scope.java, buildSrc/src/main/java/com/uber/okbuck/extension/ExternalDependenciesExtension.java
Changing dependencies like `[2.2,)` are not visible after configuration resolution but can still cause non hermetic builds. See [gradle docs](https://docs.gradle.org/current/userguide/declaring_dependencies.html)
This change adds a new extension to pick a fixed version when encountering any such dependencies before resolution and during validation. It also adds the ability to ignore changing dependencies if they are resolved with other gradle resolution mechanisms
Example configuration:
```
okbuck {
dynamicDependencyVersionMap = [
"com.google.guava:guava:19+" : "24.1.1-jre",
"com.google.guava:guava:[10.+,)" : "24.1.1-jre",
"com.google.guava:guava:[14.0, 18.0]" : "18.0",
"ml.dmlc:xgboost4j-spark:0.7-SNAPSHOT" : "0.7",
]
dynamicDependenciesToIgnore = [ …
```
=> Stricter check for changing dependencies

tooling/errorprone/createtinyjavaxtools.sh
This script goes along with these instructions for enabling Error Prone in Buck builds with OkBuck:
https://github.com/msridhar/okbuck/wiki/Using-Error-Prone-with-Buck-and-OkBuck
The script creates the `tinyjavaxtools.jar` file necessary to make Error Prone work with Buck.  The instructions above should be copied to the OkBuck wiki alongside merging this PR.
I'd like feedback on both the script and the instructions.  In particular, regarding the instructions:
* How can I tweak them to also work for Android builds (I don't think `compileJava` exists there)?
* Is there an easy-ish way to make the instructions compatible with using the Gradle Error Prone  plugin?  Or, absent that, is there at least a way to make them not break the Gradle build?  Like can we set things up so the `compileJava` …
=> Script to create tinyjavaxtools.jar, for supporting Error Prone in Buck builds

buildSrc/src/main/java/com/uber/okbuck/core/dependency/DependencyFactory.java
If okbuck is killed using sigint midway during okbuck, the depcache is not cleaned up properly by GC since they hold strong references and a new invocation of okbuck will create new instances of dependency objects which just keep getting added to the existing ones and can hang the build due to gc pauses if the heap is not big enough.
This changes both the maps/sets to dependency objects to be weak ones so they can be garbage collected even if okbuck is killed midway
=> Use weak references for dep cache

buildSrc/src/main/java/com/uber/okbuck/OkBuckGradlePlugin.java, buildSrc/src/main/java/com/uber/okbuck/core/dependency/DependencyFactory.java, buildSrc/src/main/java/com/uber/okbuck/core/dependency/DependencyUtils.java, buildSrc/src/main/java/com/uber/okbuck/core/model/base/Scope.java, buildSrc/src/main/java/com/uber/okbuck/core/model/jvm/JvmTarget.java, buildSrc/src/main/java/com/uber/okbuck/core/util/ProjectUtil.java
Using an instance of dependency factory which won't require to keep weak map.
Versionless dependency objects are being garbage collected from `unresolvedToVersionless` during okbuck run since no one keeps a strong reference to them. This makes the values disappear while the key still remains on the map. Although making vDeps just a normal set would work, but instead moving to using an instance.
=> Use dependency factory instance instead of the static class

buildSrc/src/main/java/com/uber/okbuck/core/dependency/DependencyFactory.java, buildSrc/src/main/java/com/uber/okbuck/core/dependency/DependencyUtils.java, buildSrc/src/main/java/com/uber/okbuck/core/manager/DependencyManager.java, buildSrc/src/main/java/com/uber/okbuck/core/model/base/Scope.java
Child artifacts from a resolved child dependency is added based on the `getParentArtifacts` api.
This ensures that not all child artifacts gets added to the parent but only the defined ones.
=> Use getParentArtifacts api to populate child deps

buildSrc/src/main/java/com/uber/okbuck/extension/JetifierExtension.java
This allows enabling jetifier without relying on the gradle property
=> Add flag to force enable jetifier

buildSrc/src/main/java/com/uber/okbuck/core/manager/DependencyManager.java
Since multiple configurations on the same project cannot be resolved simultaneously adding the ability to parallel resolve deps by utilizing all the available projects.
```
// okbuck config
okbuck {
// enables exported deps resolution
enableExportedDeps = true
// only resolves third party deps
thirdPartyResolutionOnly = true
}
}
// settings.gradle
include ":tooling:gradle"
include ":tooling:gradle:dummy1"
include ":tooling:gradle:dummy2"
include ":tooling:gradle:dummy3"
include ":tooling:gradle:dummy4"
include ":tooling:gradle:dummy5"
// Add a simple build.gradle file to each dummy project
apply plugin: "java"
```
Now the above setup will make a total of 8 projects available to grade (root-project, :tooling, and the ones defined explicitly) which will be able to …
=> Parallelize resolution of dependencies based on projects when resolving only third party

.buckconfig, .travis.yml, buildSrc/build.gradle, buildSrc/src/main/java/com/uber/okbuck/core/manager/KotlinManager.java, buildSrc/src/main/java/com/uber/okbuck/core/manager/ManifestMergerManager.java, buildSrc/src/main/java/com/uber/okbuck/core/model/android/AndroidInstrumentationTarget.java, buildSrc/src/main/java/com/uber/okbuck/core/model/android/AndroidTarget.java, buildSrc/src/main/java/com/uber/okbuck/core/model/jvm/JvmTarget.java, buildSrc/src/main/java/com/uber/okbuck/core/task/OkBuckTask.java, buildSrc/src/main/java/com/uber/okbuck/extension/KotlinExtension.java, buildSrc/src/main/java/com/uber/okbuck/extension/OkBuckExtension.java, buildSrc/src/main/rocker/com/uber/okbuck/template/common/Genrule.rocker.raw, buildSrc/src/main/rocker/com/uber/okbuck/template/common/HttpArchive.rocker.raw, dependencies.gradle, kotlin-app/build.gradle
- Update to latest version of Buck master
- Use kotlin compiler zip (downloaded from github) which contains all the jars and is what is used by buck now
- Use `kotlinc_plugins` to define kotlin plugins which supports source path now.
=> Update to latest buck version and use kotlin compiler zip

.travis.yml, app/build.gradle, buildSrc/build.gradle, buildSrc/src/main/java/com/uber/okbuck/OkBuckGradlePlugin.java, buildSrc/src/main/java/com/uber/okbuck/composer/android/AndroidLibraryRuleComposer.java, buildSrc/src/main/java/com/uber/okbuck/composer/android/AndroidModuleRuleComposer.java, buildSrc/src/main/java/com/uber/okbuck/composer/android/AndroidTestRuleComposer.java, buildSrc/src/main/java/com/uber/okbuck/composer/android/ExopackageAndroidLibraryRuleComposer.java, buildSrc/src/main/java/com/uber/okbuck/core/manager/BuckManager.java, buildSrc/src/main/java/com/uber/okbuck/core/manager/D8Manager.java, buildSrc/src/main/java/com/uber/okbuck/extension/OkBuckExtension.java, dependencies.gradle, dummylibrary/build.gradle, java-app/build.gradle, kotlin-app/build.gradle, libraries/javalibrary/build.gradle, libraries/kotlinlibrary/build.gradle, libraries/lintErrorLibrary/build.gradle
=> Make okbuck Java 11 Compatible

.buckconfig, buckw, buildSrc/src/main/java/com/uber/okbuck/core/model/jvm/JvmTarget.java, buildSrc/src/main/java/com/uber/okbuck/core/task/OkBuckTask.java, buildSrc/src/main/java/com/uber/okbuck/core/util/FileUtil.java, buildSrc/src/main/java/com/uber/okbuck/extension/OkBuckExtension.java, buildSrc/src/main/rocker/com/uber/okbuck/template/config/BuckWrapper.rocker.raw, dependencies.gradle, kotlin-app/src/test/java/com/uber/okbuck/example/Coffee.kt, libraries/kotlinlibrary/src/main/java/demo/helloWorld.kt
Don't pass okbuck.buckconfig explicity to buck in the
buckwrapper to allow overriding configs in .okbuck.buckconfig
Bump Kotlin to 1.4.10 and incorporate Subplugin changes
Bump buck to a68ef0d834eec5fe381cb3e8e8612ba9fa42a09d. The latest version 
has changes to kotlin params which will require further changes when updating.
Resolves https://github.com/uber/okbuck/issues/927
=> Add .okbuck.buckconfig to .buckconfig

.gitignore, buildSrc/src/main/java/com/uber/okbuck/OkBuckGradlePlugin.java, buildSrc/src/main/java/com/uber/okbuck/composer/common/BazelHttpFileRuleComposer.java, buildSrc/src/main/java/com/uber/okbuck/core/dependency/OExternalDependency.java, buildSrc/src/main/java/com/uber/okbuck/core/manager/BuckFileManager.java, buildSrc/src/main/java/com/uber/okbuck/core/manager/DependencyManager.java, buildSrc/src/main/java/com/uber/okbuck/core/model/base/RuleType.java, buildSrc/src/main/java/com/uber/okbuck/core/task/OkBuckTask.java, buildSrc/src/main/java/com/uber/okbuck/extension/ExternalDependenciesExtension.java, buildSrc/src/main/java/com/uber/okbuck/extension/RuleOverridesExtension.java, buildSrc/src/main/rocker/com/uber/okbuck/template/common/BazelFunctionRule.rocker.raw, buildSrc/src/main/rocker/com/uber/okbuck/template/common/BazelHttpFile.rocker.raw, buildSrc/src/main/rocker/com/uber/okbuck/template/config/OkbuckPrebuilt.rocker.raw
Below will generate `defs.bzl` containing Bazel http_file rules to enable downloading of 3rdparty deps.
```
okbuck {
externalDependecies {
bazelDeps = true
}
}
```
=> Add support for generating http_file rules for bazel

buildSrc/src/main/java/com/uber/okbuck/core/task/OkBuckTask.java, buildSrc/src/main/java/com/uber/okbuck/extension/OkBuckExtension.java
This allows one to configure the inclusion of `.okbuck.buckconfig` to top level `.buckconfig`. The default is to always include it if it is not present
=> Add ability to configure okbuck buckconfig inclusion

buildSrc/src/main/rocker/com/uber/okbuck/template/config/OkbuckAndroidModules.rocker.raw
Used to work around resource limit in large apps. Indeed, too many resources ids in dummy R.java (~12k) will cause java compiler to fail ('method too large'). By specifying a smaller set of dependencies, used only for resources target, this problem can be resolved.
=> Enable android_library() targets to specify alternate deps for resources

README-zh.md, README.md, buildSrc/build.gradle, buildSrc/gradle.properties, buildSrc/src/main/rocker/com/uber/okbuck/template/config/OkbuckAndroidModules.rocker.raw, gradle/gradle-mvn-push.gradle
Switch standard way of publishing to maven + prepare to publish V0.52.4
=> Switch standard way of publishing to maven + prepare to publish V0.52.4

README-zh.md, build.gradle, buildSrc/build.gradle, buildSrc/src/main/java/com/uber/okbuck/core/manager/RobolectricManager.java, buildSrc/src/main/java/com/uber/okbuck/extension/ExternalDependenciesExtension.java, buildSrc/src/main/java/com/uber/okbuck/extension/TestExtension.java, dependencies.gradle
Master is currently not in state to release a new version of OKbuck without reverting the work towards upgrading Gradle.
I've created a release branch off of the last tag (v0.52.3) and this is a pull request against that branch. We can cut this release build 0.52.4 from the release branch, then separately patch this diff against master which will require some rebase conflict changes.
This was tested locally against the Uber Android monorepo.
-4.7.3 is needed to address ARM compatibility on m1, as it carries a patch for sqlite4java.
-They also introduced preinstrumented jars which should save 10-12 seconds per test process instantiation.
=> Adding support for Robolectric 4.7.3 and preinstrumented jars

build.gradle, buildSrc/src/main/java/com/uber/okbuck/core/manager/RobolectricManager.java, buildSrc/src/main/java/com/uber/okbuck/extension/ExternalDependenciesExtension.java, buildSrc/src/main/java/com/uber/okbuck/extension/TestExtension.java, dependencies.gradle
Rebasing master on release to include Robolectric 4.7.3 and preinstrumented jars (#958).
We should be able to kill the release branch after this since a path to gradle 7 is unlocked in uber internal monorepos
=> Rebase release branch

buildSrc/src/main/java/com/uber/okbuck/extension/JetifierExtension.java
The current Jetifier Preprocessor version specified in the tooling has a bug in the default rules which changes the constant values as well. A specific use case is:
_android.support.customtabs.action.CustomTabsService_ to _androidx.support.customtabs.action.CustomTabsService_
The issue was reported in the Android AOSP  -> https://android-review.googlesource.com/875343/. It has been fixed in the Jetifier version 1.0.0-beta03. 
**Change Log**:
https://developer.android.com/jetpack/androidx/releases/jetifier#1.0.0-beta03
https://android-review.googlesource.com/c/platform/frameworks/support/+/875343/
=> Upgrade Jetifier to 1.0.0-beta03

buildSrc/gradle.properties, buildSrc/src/main/java/com/uber/okbuck/OkBuckGradlePlugin.java, buildSrc/src/main/java/com/uber/okbuck/core/dependency/exporter/DependencyExporter.java, buildSrc/src/main/java/com/uber/okbuck/core/dependency/exporter/DependencyExporterModel.java, buildSrc/src/main/java/com/uber/okbuck/core/dependency/exporter/ExporterException.java, buildSrc/src/main/java/com/uber/okbuck/core/dependency/exporter/JsonDependencyExporter.java, buildSrc/src/main/java/com/uber/okbuck/core/manager/DependencyManager.java, buildSrc/src/main/java/com/uber/okbuck/core/util/ProjectUtil.java, buildSrc/src/main/java/com/uber/okbuck/extension/ExportDependenciesExtension.java, buildSrc/src/main/java/com/uber/okbuck/extension/OkBuckExtension.java
**Description**:  Add support for exporting raw dependencies
plugin can accept the following configuration
```
{
okbuck {
...
exportDependencies { enabled = false, file = ".okbuck/raw-deps" }
...
}
```
Supports exporting raw dependencies in JSON format.
```
./gradlew okbuck
```
Example exported json snippet:
```
[
{
"name": "hadoop-aws",
"version": "2.8.2",
"group": "org.apache.hadoop",
"force": false,
"excludeRules": [
"javax.servlet",
"org.mortbay.jetty",
"slf4j-log4j12"
],
"transitive": true
},
....
]
```
=> feat: Add support for exporting raw dependencies

buildSrc/src/main/java/com/uber/okbuck/core/dependency/exporter/JsonDependencyExporter.java
Create parent directories for exportDependencies.file path if it doesn't exists.
https://github.com/uber/okbuck/issues/975
=> Create parent directories if it doesn't exists

README-zh.md, README.md, Usage.md, buildSrc/src/main/java/com/uber/okbuck/core/manager/DependencyManager.java, buildSrc/src/main/java/com/uber/okbuck/core/util/FileUtil.java, buildSrc/src/main/java/com/uber/okbuck/extension/ExternalDependenciesExtension.java
Add config cleanCacheDir which controls whether to delete the cache dir or only the existing dependency rules files, before generating the dependency rule files
Usage
```
okbuck {
... 
...
cleanCacheDir = false
}
...
}
```
=> Add config cleanCacheDir 

buildSrc/src/main/rocker/com/uber/okbuck/template/config/OkbuckTargets.rocker.raw
Android Lint current generates it's tmp files inside /tmp for the system, whereas it should be using buck-out's declared $TMP which lives under buck-out.
=> Move lint tmp file to buck-out/tmp

buildSrc/src/main/rocker/com/uber/okbuck/template/config/OkbuckTargets.rocker.raw
Android Lint has always had a leftover tmp.bak file after it's run which add up over time. After moving this to buck-out's $TMP, this was obvious.
=> Delete tmp file and .bak file for android lint runs

CHANGELOG.md, README-zh.md, README.md, buildSrc/gradle.properties, gradle.properties
The Uber open source signing certificate was accidentally compromised.  That old certificate has been invalidated, and a new certificate was generated.  This updates the signed code in the Sonatype repository (maven).
No other code changes are in this release.
=> Update signing certificate for Sonatype

.github/workflows/ci.yml, .github/workflows/fossa.yaml, README-zh.md, Usage.md, app/build.gradle, app/src/main/java/com/uber/okbuck/example/MainActivity.java, app/src/main/java/com/uber/okbuck/example/MyApp.java, build.gradle, dependencies.gradle
**Description**
- Update the runner image to `ubuntu-24.04`. `ubuntu-20.04` is now deprecated: https://github.com/actions/runner-images/issues/11101
- Update `actions/checkout` to v4.
- Update `actions/setup-java` to v4 and set the distribution to `temurin`.
**Note**
- It's possible to use `ubuntu-latest` instead of `ubuntu-24.04`. Let me know which option you prefer.
- `actions/setup-java` supports a [wide range of distributions](https://github.com/actions/setup-java#supported-distributions). Let me know if you'd prefer to use something else than `temurin`.
=> Update actions used in GitHub Actions workflows
